image: aergus/latex
before_script:
 - apt-get update --yes
 - apt-get install --yes g++ make cmake ghostscript latex2html gfortran
build:
  script:
  - make util
  - make
  artifacts:
    paths:
    - bin/generator