image: gcc

build:
  stage: build
  artifacts:
    untracked: true
  script:
    - make

test1:
  stage: test
  dependencies:
    - build
  script:
    - .generate.py -q -N 1 -n 10000 -e 10 -o
  artifacts:
    paths:
      - "*.cfg" 
      - "*.grid" 
      - "*.log"
      - "*.txt"

test2:
  stage: test
  dependencies:
    - build
  script:
    - .generate.py -q -N 10 -n 1000000 -e 10 -o
  artifacts:
    paths:
      - "*.cfg" 
      - "*.grid" 
      - "*.log"
      - "*.txt"
      - "*.lhef"