image: gcc

stages:
  - build
  - test

compile:
  stage: build
  script: make
    
run:
  stage: test
  script: ./macros/generate.py -q -N 1 -n 10000 -e 10 -o
  artifacts:
    paths:
      - ./*.cfg
      - ./*.grid
      - ./*.log
      - ./*.txt
