image: rootproject/root-ubuntu16
before_script:
 - sudo apt-get update --yes
 - sudo apt-get install --yes texlive gcc g++ make cmake ghostscript latex2html gfortran xpdf imagemagick
 - echo "Finished before script"
build:
  script:
  - make util
  - export LD_LIBRARY_PATH="/builds/declan.millar/prophet/util/build/src:$LD_LIBRARY_PATH"
  - nm -Ca util/build/src/libRootTuple.so
  - make