image: ubuntu18
before_script:
 - apt-get update --yes
 - apt-get install --yes cmake texlive ghostscript latex2html root
build:
  script:
  - make util
  - make
  artifacts:
    paths:
    - bin/generator