image: rootproject/root-ubuntu16
before_script:
 - sudo apt-get update --yes
 - sudo apt-get install --yes texlive gcc g++ make cmake ghostscript latex2html gfortran xpdf imagemagick
 - echo "Finished before script"
build:
  script:
  - make util
  - nm -Ca util/build/src/libRootTuple.so
  - make
  artifacts:
    paths:
    - bin/generator