image: rootproject/root-ubuntu16
before_script:
 - apt-get update --yes
 # - apt-get install --yes g++ make cmake ghostscript latex2html gfortran
 # - cd ..
 # - wget https://root.cern.ch/download/root_v6.14.06.Linux-ubuntu18-x86_64-gcc7.3.tar.gz
 # - tar xvfz root_v6.14.06.Linux-ubuntu18-x86_64-gcc7.3.tar.gz
 # - pwd
 # - ls root/bin/thisroot.sh
 # - sed -i '1s/^/set -x\n/' root/bin/thisroot.sh
 # - source root/bin/thisroot.sh
 - echo "Finished before script"
build:
  script:
  - make util
  - make
  artifacts:
    paths:
    - bin/generator