image: ubuntu
before_script:
 - apt-get update --yes
 - apt-get install --yes cmake texlive-full ghostscript latex2html
build:
  script:
  - make util
  - make
  artifacts:
    paths:
    - bin/generator