function sqq_bbtatavtvt(p1, p2, p3, p4, p5, p6, p7, p8)

    ! function generated by madgraph
    ! returns amplitude squared summed/avg over colors
    ! and helicities
    ! for the point in phase space p1,p2,p3,p4,...

    ! for process : q q~  -> b b~ e+ e- v v~

    implicit none

    real(kind=default) :: sqq_bbtatavtvt

    ! constants
    integer, parameter :: nexternal = 8, ncomb = 256

    ! arguments

    real(kind=default) :: p1(0:3),p2(0:3),p3(0:3),p4(0:3),p5(0:3),p6(0:3),p7(0:3),p8(0:3)

    ! local variables

    integer :: nhel(nexternal,ncomb),ntry
    real(kind=default) :: t
    real(kind=default) :: qq_bbtatavtvt
    integer :: ihel
    logical :: goodhel(ncomb)
    data goodhel/ncomb* .false. /
    data ntry/0/
    data (nhel(ihel,  1),ihel=1,8) / -1, -1, -1, -1, -1, -1, -1, -1/
    data (nhel(ihel,  2),ihel=1,8) / -1, -1, -1, -1, -1, -1, -1,  1/
    data (nhel(ihel,  3),ihel=1,8) / -1, -1, -1, -1, -1, -1,  1, -1/
    data (nhel(ihel,  4),ihel=1,8) / -1, -1, -1, -1, -1, -1,  1,  1/
    data (nhel(ihel,  5),ihel=1,8) / -1, -1, -1, -1, -1,  1, -1, -1/
    data (nhel(ihel,  6),ihel=1,8) / -1, -1, -1, -1, -1,  1, -1,  1/
    data (nhel(ihel,  7),ihel=1,8) / -1, -1, -1, -1, -1,  1,  1, -1/
    data (nhel(ihel,  8),ihel=1,8) / -1, -1, -1, -1, -1,  1,  1,  1/
    data (nhel(ihel,  9),ihel=1,8) / -1, -1, -1, -1,  1, -1, -1, -1/
    data (nhel(ihel, 10),ihel=1,8) / -1, -1, -1, -1,  1, -1, -1,  1/
    data (nhel(ihel, 11),ihel=1,8) / -1, -1, -1, -1,  1, -1,  1, -1/
    data (nhel(ihel, 12),ihel=1,8) / -1, -1, -1, -1,  1, -1,  1,  1/
    data (nhel(ihel, 13),ihel=1,8) / -1, -1, -1, -1,  1,  1, -1, -1/
    data (nhel(ihel, 14),ihel=1,8) / -1, -1, -1, -1,  1,  1, -1,  1/
    data (nhel(ihel, 15),ihel=1,8) / -1, -1, -1, -1,  1,  1,  1, -1/
    data (nhel(ihel, 16),ihel=1,8) / -1, -1, -1, -1,  1,  1,  1,  1/
    data (nhel(ihel, 17),ihel=1,8) / -1, -1, -1,  1, -1, -1, -1, -1/
    data (nhel(ihel, 18),ihel=1,8) / -1, -1, -1,  1, -1, -1, -1,  1/
    data (nhel(ihel, 19),ihel=1,8) / -1, -1, -1,  1, -1, -1,  1, -1/
    data (nhel(ihel, 20),ihel=1,8) / -1, -1, -1,  1, -1, -1,  1,  1/
    data (nhel(ihel, 21),ihel=1,8) / -1, -1, -1,  1, -1,  1, -1, -1/
    data (nhel(ihel, 22),ihel=1,8) / -1, -1, -1,  1, -1,  1, -1,  1/
    data (nhel(ihel, 23),ihel=1,8) / -1, -1, -1,  1, -1,  1,  1, -1/
    data (nhel(ihel, 24),ihel=1,8) / -1, -1, -1,  1, -1,  1,  1,  1/
    data (nhel(ihel, 25),ihel=1,8) / -1, -1, -1,  1,  1, -1, -1, -1/
    data (nhel(ihel, 26),ihel=1,8) / -1, -1, -1,  1,  1, -1, -1,  1/
    data (nhel(ihel, 27),ihel=1,8) / -1, -1, -1,  1,  1, -1,  1, -1/
    data (nhel(ihel, 28),ihel=1,8) / -1, -1, -1,  1,  1, -1,  1,  1/
    data (nhel(ihel, 29),ihel=1,8) / -1, -1, -1,  1,  1,  1, -1, -1/
    data (nhel(ihel, 30),ihel=1,8) / -1, -1, -1,  1,  1,  1, -1,  1/
    data (nhel(ihel, 31),ihel=1,8) / -1, -1, -1,  1,  1,  1,  1, -1/
    data (nhel(ihel, 32),ihel=1,8) / -1, -1, -1,  1,  1,  1,  1,  1/
    data (nhel(ihel, 33),ihel=1,8) / -1, -1,  1, -1, -1, -1, -1, -1/
    data (nhel(ihel, 34),ihel=1,8) / -1, -1,  1, -1, -1, -1, -1,  1/
    data (nhel(ihel, 35),ihel=1,8) / -1, -1,  1, -1, -1, -1,  1, -1/
    data (nhel(ihel, 36),ihel=1,8) / -1, -1,  1, -1, -1, -1,  1,  1/
    data (nhel(ihel, 37),ihel=1,8) / -1, -1,  1, -1, -1,  1, -1, -1/
    data (nhel(ihel, 38),ihel=1,8) / -1, -1,  1, -1, -1,  1, -1,  1/
    data (nhel(ihel, 39),ihel=1,8) / -1, -1,  1, -1, -1,  1,  1, -1/
    data (nhel(ihel, 40),ihel=1,8) / -1, -1,  1, -1, -1,  1,  1,  1/
    data (nhel(ihel, 41),ihel=1,8) / -1, -1,  1, -1,  1, -1, -1, -1/
    data (nhel(ihel, 42),ihel=1,8) / -1, -1,  1, -1,  1, -1, -1,  1/
    data (nhel(ihel, 43),ihel=1,8) / -1, -1,  1, -1,  1, -1,  1, -1/
    data (nhel(ihel, 44),ihel=1,8) / -1, -1,  1, -1,  1, -1,  1,  1/
    data (nhel(ihel, 45),ihel=1,8) / -1, -1,  1, -1,  1,  1, -1, -1/
    data (nhel(ihel, 46),ihel=1,8) / -1, -1,  1, -1,  1,  1, -1,  1/
    data (nhel(ihel, 47),ihel=1,8) / -1, -1,  1, -1,  1,  1,  1, -1/
    data (nhel(ihel, 48),ihel=1,8) / -1, -1,  1, -1,  1,  1,  1,  1/
    data (nhel(ihel, 49),ihel=1,8) / -1, -1,  1,  1, -1, -1, -1, -1/
    data (nhel(ihel, 50),ihel=1,8) / -1, -1,  1,  1, -1, -1, -1,  1/
    data (nhel(ihel, 51),ihel=1,8) / -1, -1,  1,  1, -1, -1,  1, -1/
    data (nhel(ihel, 52),ihel=1,8) / -1, -1,  1,  1, -1, -1,  1,  1/
    data (nhel(ihel, 53),ihel=1,8) / -1, -1,  1,  1, -1,  1, -1, -1/
    data (nhel(ihel, 54),ihel=1,8) / -1, -1,  1,  1, -1,  1, -1,  1/
    data (nhel(ihel, 55),ihel=1,8) / -1, -1,  1,  1, -1,  1,  1, -1/
    data (nhel(ihel, 56),ihel=1,8) / -1, -1,  1,  1, -1,  1,  1,  1/
    data (nhel(ihel, 57),ihel=1,8) / -1, -1,  1,  1,  1, -1, -1, -1/
    data (nhel(ihel, 58),ihel=1,8) / -1, -1,  1,  1,  1, -1, -1,  1/
    data (nhel(ihel, 59),ihel=1,8) / -1, -1,  1,  1,  1, -1,  1, -1/
    data (nhel(ihel, 60),ihel=1,8) / -1, -1,  1,  1,  1, -1,  1,  1/
    data (nhel(ihel, 61),ihel=1,8) / -1, -1,  1,  1,  1,  1, -1, -1/
    data (nhel(ihel, 62),ihel=1,8) / -1, -1,  1,  1,  1,  1, -1,  1/
    data (nhel(ihel, 63),ihel=1,8) / -1, -1,  1,  1,  1,  1,  1, -1/
    data (nhel(ihel, 64),ihel=1,8) / -1, -1,  1,  1,  1,  1,  1,  1/
    data (nhel(ihel, 65),ihel=1,8) / -1,  1, -1, -1, -1, -1, -1, -1/
    data (nhel(ihel, 66),ihel=1,8) / -1,  1, -1, -1, -1, -1, -1,  1/
    data (nhel(ihel, 67),ihel=1,8) / -1,  1, -1, -1, -1, -1,  1, -1/
    data (nhel(ihel, 68),ihel=1,8) / -1,  1, -1, -1, -1, -1,  1,  1/
    data (nhel(ihel, 69),ihel=1,8) / -1,  1, -1, -1, -1,  1, -1, -1/
    data (nhel(ihel, 70),ihel=1,8) / -1,  1, -1, -1, -1,  1, -1,  1/
    data (nhel(ihel, 71),ihel=1,8) / -1,  1, -1, -1, -1,  1,  1, -1/
    data (nhel(ihel, 72),ihel=1,8) / -1,  1, -1, -1, -1,  1,  1,  1/
    data (nhel(ihel, 73),ihel=1,8) / -1,  1, -1, -1,  1, -1, -1, -1/
    data (nhel(ihel, 74),ihel=1,8) / -1,  1, -1, -1,  1, -1, -1,  1/
    data (nhel(ihel, 75),ihel=1,8) / -1,  1, -1, -1,  1, -1,  1, -1/
    data (nhel(ihel, 76),ihel=1,8) / -1,  1, -1, -1,  1, -1,  1,  1/
    data (nhel(ihel, 77),ihel=1,8) / -1,  1, -1, -1,  1,  1, -1, -1/
    data (nhel(ihel, 78),ihel=1,8) / -1,  1, -1, -1,  1,  1, -1,  1/
    data (nhel(ihel, 79),ihel=1,8) / -1,  1, -1, -1,  1,  1,  1, -1/
    data (nhel(ihel, 80),ihel=1,8) / -1,  1, -1, -1,  1,  1,  1,  1/
    data (nhel(ihel, 81),ihel=1,8) / -1,  1, -1,  1, -1, -1, -1, -1/
    data (nhel(ihel, 82),ihel=1,8) / -1,  1, -1,  1, -1, -1, -1,  1/
    data (nhel(ihel, 83),ihel=1,8) / -1,  1, -1,  1, -1, -1,  1, -1/
    data (nhel(ihel, 84),ihel=1,8) / -1,  1, -1,  1, -1, -1,  1,  1/
    data (nhel(ihel, 85),ihel=1,8) / -1,  1, -1,  1, -1,  1, -1, -1/
    data (nhel(ihel, 86),ihel=1,8) / -1,  1, -1,  1, -1,  1, -1,  1/
    data (nhel(ihel, 87),ihel=1,8) / -1,  1, -1,  1, -1,  1,  1, -1/
    data (nhel(ihel, 88),ihel=1,8) / -1,  1, -1,  1, -1,  1,  1,  1/
    data (nhel(ihel, 89),ihel=1,8) / -1,  1, -1,  1,  1, -1, -1, -1/
    data (nhel(ihel, 90),ihel=1,8) / -1,  1, -1,  1,  1, -1, -1,  1/
    data (nhel(ihel, 91),ihel=1,8) / -1,  1, -1,  1,  1, -1,  1, -1/
    data (nhel(ihel, 92),ihel=1,8) / -1,  1, -1,  1,  1, -1,  1,  1/
    data (nhel(ihel, 93),ihel=1,8) / -1,  1, -1,  1,  1,  1, -1, -1/
    data (nhel(ihel, 94),ihel=1,8) / -1,  1, -1,  1,  1,  1, -1,  1/
    data (nhel(ihel, 95),ihel=1,8) / -1,  1, -1,  1,  1,  1,  1, -1/
    data (nhel(ihel, 96),ihel=1,8) / -1,  1, -1,  1,  1,  1,  1,  1/
    data (nhel(ihel, 97),ihel=1,8) / -1,  1,  1, -1, -1, -1, -1, -1/
    data (nhel(ihel, 98),ihel=1,8) / -1,  1,  1, -1, -1, -1, -1,  1/
    data (nhel(ihel, 99),ihel=1,8) / -1,  1,  1, -1, -1, -1,  1, -1/
    data (nhel(ihel,100),ihel=1,8) / -1,  1,  1, -1, -1, -1,  1,  1/
    data (nhel(ihel,101),ihel=1,8) / -1,  1,  1, -1, -1,  1, -1, -1/
    data (nhel(ihel,102),ihel=1,8) / -1,  1,  1, -1, -1,  1, -1,  1/
    data (nhel(ihel,103),ihel=1,8) / -1,  1,  1, -1, -1,  1,  1, -1/
    data (nhel(ihel,104),ihel=1,8) / -1,  1,  1, -1, -1,  1,  1,  1/
    data (nhel(ihel,105),ihel=1,8) / -1,  1,  1, -1,  1, -1, -1, -1/
    data (nhel(ihel,106),ihel=1,8) / -1,  1,  1, -1,  1, -1, -1,  1/
    data (nhel(ihel,107),ihel=1,8) / -1,  1,  1, -1,  1, -1,  1, -1/
    data (nhel(ihel,108),ihel=1,8) / -1,  1,  1, -1,  1, -1,  1,  1/
    data (nhel(ihel,109),ihel=1,8) / -1,  1,  1, -1,  1,  1, -1, -1/
    data (nhel(ihel,110),ihel=1,8) / -1,  1,  1, -1,  1,  1, -1,  1/
    data (nhel(ihel,111),ihel=1,8) / -1,  1,  1, -1,  1,  1,  1, -1/
    data (nhel(ihel,112),ihel=1,8) / -1,  1,  1, -1,  1,  1,  1,  1/
    data (nhel(ihel,113),ihel=1,8) / -1,  1,  1,  1, -1, -1, -1, -1/
    data (nhel(ihel,114),ihel=1,8) / -1,  1,  1,  1, -1, -1, -1,  1/
    data (nhel(ihel,115),ihel=1,8) / -1,  1,  1,  1, -1, -1,  1, -1/
    data (nhel(ihel,116),ihel=1,8) / -1,  1,  1,  1, -1, -1,  1,  1/
    data (nhel(ihel,117),ihel=1,8) / -1,  1,  1,  1, -1,  1, -1, -1/
    data (nhel(ihel,118),ihel=1,8) / -1,  1,  1,  1, -1,  1, -1,  1/
    data (nhel(ihel,119),ihel=1,8) / -1,  1,  1,  1, -1,  1,  1, -1/
    data (nhel(ihel,120),ihel=1,8) / -1,  1,  1,  1, -1,  1,  1,  1/
    data (nhel(ihel,121),ihel=1,8) / -1,  1,  1,  1,  1, -1, -1, -1/
    data (nhel(ihel,122),ihel=1,8) / -1,  1,  1,  1,  1, -1, -1,  1/
    data (nhel(ihel,123),ihel=1,8) / -1,  1,  1,  1,  1, -1,  1, -1/
    data (nhel(ihel,124),ihel=1,8) / -1,  1,  1,  1,  1, -1,  1,  1/
    data (nhel(ihel,125),ihel=1,8) / -1,  1,  1,  1,  1,  1, -1, -1/
    data (nhel(ihel,126),ihel=1,8) / -1,  1,  1,  1,  1,  1, -1,  1/
    data (nhel(ihel,127),ihel=1,8) / -1,  1,  1,  1,  1,  1,  1, -1/
    data (nhel(ihel,128),ihel=1,8) / -1,  1,  1,  1,  1,  1,  1,  1/
    data (nhel(ihel,129),ihel=1,8) /  1, -1, -1, -1, -1, -1, -1, -1/
    data (nhel(ihel,130),ihel=1,8) /  1, -1, -1, -1, -1, -1, -1,  1/
    data (nhel(ihel,131),ihel=1,8) /  1, -1, -1, -1, -1, -1,  1, -1/
    data (nhel(ihel,132),ihel=1,8) /  1, -1, -1, -1, -1, -1,  1,  1/
    data (nhel(ihel,133),ihel=1,8) /  1, -1, -1, -1, -1,  1, -1, -1/
    data (nhel(ihel,134),ihel=1,8) /  1, -1, -1, -1, -1,  1, -1,  1/
    data (nhel(ihel,135),ihel=1,8) /  1, -1, -1, -1, -1,  1,  1, -1/
    data (nhel(ihel,136),ihel=1,8) /  1, -1, -1, -1, -1,  1,  1,  1/
    data (nhel(ihel,137),ihel=1,8) /  1, -1, -1, -1,  1, -1, -1, -1/
    data (nhel(ihel,138),ihel=1,8) /  1, -1, -1, -1,  1, -1, -1,  1/
    data (nhel(ihel,139),ihel=1,8) /  1, -1, -1, -1,  1, -1,  1, -1/
    data (nhel(ihel,140),ihel=1,8) /  1, -1, -1, -1,  1, -1,  1,  1/
    data (nhel(ihel,141),ihel=1,8) /  1, -1, -1, -1,  1,  1, -1, -1/
    data (nhel(ihel,142),ihel=1,8) /  1, -1, -1, -1,  1,  1, -1,  1/
    data (nhel(ihel,143),ihel=1,8) /  1, -1, -1, -1,  1,  1,  1, -1/
    data (nhel(ihel,144),ihel=1,8) /  1, -1, -1, -1,  1,  1,  1,  1/
    data (nhel(ihel,145),ihel=1,8) /  1, -1, -1,  1, -1, -1, -1, -1/
    data (nhel(ihel,146),ihel=1,8) /  1, -1, -1,  1, -1, -1, -1,  1/
    data (nhel(ihel,147),ihel=1,8) /  1, -1, -1,  1, -1, -1,  1, -1/
    data (nhel(ihel,148),ihel=1,8) /  1, -1, -1,  1, -1, -1,  1,  1/
    data (nhel(ihel,149),ihel=1,8) /  1, -1, -1,  1, -1,  1, -1, -1/
    data (nhel(ihel,150),ihel=1,8) /  1, -1, -1,  1, -1,  1, -1,  1/
    data (nhel(ihel,151),ihel=1,8) /  1, -1, -1,  1, -1,  1,  1, -1/
    data (nhel(ihel,152),ihel=1,8) /  1, -1, -1,  1, -1,  1,  1,  1/
    data (nhel(ihel,153),ihel=1,8) /  1, -1, -1,  1,  1, -1, -1, -1/
    data (nhel(ihel,154),ihel=1,8) /  1, -1, -1,  1,  1, -1, -1,  1/
    data (nhel(ihel,155),ihel=1,8) /  1, -1, -1,  1,  1, -1,  1, -1/
    data (nhel(ihel,156),ihel=1,8) /  1, -1, -1,  1,  1, -1,  1,  1/
    data (nhel(ihel,157),ihel=1,8) /  1, -1, -1,  1,  1,  1, -1, -1/
    data (nhel(ihel,158),ihel=1,8) /  1, -1, -1,  1,  1,  1, -1,  1/
    data (nhel(ihel,159),ihel=1,8) /  1, -1, -1,  1,  1,  1,  1, -1/
    data (nhel(ihel,160),ihel=1,8) /  1, -1, -1,  1,  1,  1,  1,  1/
    data (nhel(ihel,161),ihel=1,8) /  1, -1,  1, -1, -1, -1, -1, -1/
    data (nhel(ihel,162),ihel=1,8) /  1, -1,  1, -1, -1, -1, -1,  1/
    data (nhel(ihel,163),ihel=1,8) /  1, -1,  1, -1, -1, -1,  1, -1/
    data (nhel(ihel,164),ihel=1,8) /  1, -1,  1, -1, -1, -1,  1,  1/
    data (nhel(ihel,165),ihel=1,8) /  1, -1,  1, -1, -1,  1, -1, -1/
    data (nhel(ihel,166),ihel=1,8) /  1, -1,  1, -1, -1,  1, -1,  1/
    data (nhel(ihel,167),ihel=1,8) /  1, -1,  1, -1, -1,  1,  1, -1/
    data (nhel(ihel,168),ihel=1,8) /  1, -1,  1, -1, -1,  1,  1,  1/
    data (nhel(ihel,169),ihel=1,8) /  1, -1,  1, -1,  1, -1, -1, -1/
    data (nhel(ihel,170),ihel=1,8) /  1, -1,  1, -1,  1, -1, -1,  1/
    data (nhel(ihel,171),ihel=1,8) /  1, -1,  1, -1,  1, -1,  1, -1/
    data (nhel(ihel,172),ihel=1,8) /  1, -1,  1, -1,  1, -1,  1,  1/
    data (nhel(ihel,173),ihel=1,8) /  1, -1,  1, -1,  1,  1, -1, -1/
    data (nhel(ihel,174),ihel=1,8) /  1, -1,  1, -1,  1,  1, -1,  1/
    data (nhel(ihel,175),ihel=1,8) /  1, -1,  1, -1,  1,  1,  1, -1/
    data (nhel(ihel,176),ihel=1,8) /  1, -1,  1, -1,  1,  1,  1,  1/
    data (nhel(ihel,177),ihel=1,8) /  1, -1,  1,  1, -1, -1, -1, -1/
    data (nhel(ihel,178),ihel=1,8) /  1, -1,  1,  1, -1, -1, -1,  1/
    data (nhel(ihel,179),ihel=1,8) /  1, -1,  1,  1, -1, -1,  1, -1/
    data (nhel(ihel,180),ihel=1,8) /  1, -1,  1,  1, -1, -1,  1,  1/
    data (nhel(ihel,181),ihel=1,8) /  1, -1,  1,  1, -1,  1, -1, -1/
    data (nhel(ihel,182),ihel=1,8) /  1, -1,  1,  1, -1,  1, -1,  1/
    data (nhel(ihel,183),ihel=1,8) /  1, -1,  1,  1, -1,  1,  1, -1/
    data (nhel(ihel,184),ihel=1,8) /  1, -1,  1,  1, -1,  1,  1,  1/
    data (nhel(ihel,185),ihel=1,8) /  1, -1,  1,  1,  1, -1, -1, -1/
    data (nhel(ihel,186),ihel=1,8) /  1, -1,  1,  1,  1, -1, -1,  1/
    data (nhel(ihel,187),ihel=1,8) /  1, -1,  1,  1,  1, -1,  1, -1/
    data (nhel(ihel,188),ihel=1,8) /  1, -1,  1,  1,  1, -1,  1,  1/
    data (nhel(ihel,189),ihel=1,8) /  1, -1,  1,  1,  1,  1, -1, -1/
    data (nhel(ihel,190),ihel=1,8) /  1, -1,  1,  1,  1,  1, -1,  1/
    data (nhel(ihel,191),ihel=1,8) /  1, -1,  1,  1,  1,  1,  1, -1/
    data (nhel(ihel,192),ihel=1,8) /  1, -1,  1,  1,  1,  1,  1,  1/
    data (nhel(ihel,193),ihel=1,8) /  1,  1, -1, -1, -1, -1, -1, -1/
    data (nhel(ihel,194),ihel=1,8) /  1,  1, -1, -1, -1, -1, -1,  1/
    data (nhel(ihel,195),ihel=1,8) /  1,  1, -1, -1, -1, -1,  1, -1/
    data (nhel(ihel,196),ihel=1,8) /  1,  1, -1, -1, -1, -1,  1,  1/
    data (nhel(ihel,197),ihel=1,8) /  1,  1, -1, -1, -1,  1, -1, -1/
    data (nhel(ihel,198),ihel=1,8) /  1,  1, -1, -1, -1,  1, -1,  1/
    data (nhel(ihel,199),ihel=1,8) /  1,  1, -1, -1, -1,  1,  1, -1/
    data (nhel(ihel,200),ihel=1,8) /  1,  1, -1, -1, -1,  1,  1,  1/
    data (nhel(ihel,201),ihel=1,8) /  1,  1, -1, -1,  1, -1, -1, -1/
    data (nhel(ihel,202),ihel=1,8) /  1,  1, -1, -1,  1, -1, -1,  1/
    data (nhel(ihel,203),ihel=1,8) /  1,  1, -1, -1,  1, -1,  1, -1/
    data (nhel(ihel,204),ihel=1,8) /  1,  1, -1, -1,  1, -1,  1,  1/
    data (nhel(ihel,205),ihel=1,8) /  1,  1, -1, -1,  1,  1, -1, -1/
    data (nhel(ihel,206),ihel=1,8) /  1,  1, -1, -1,  1,  1, -1,  1/
    data (nhel(ihel,207),ihel=1,8) /  1,  1, -1, -1,  1,  1,  1, -1/
    data (nhel(ihel,208),ihel=1,8) /  1,  1, -1, -1,  1,  1,  1,  1/
    data (nhel(ihel,209),ihel=1,8) /  1,  1, -1,  1, -1, -1, -1, -1/
    data (nhel(ihel,210),ihel=1,8) /  1,  1, -1,  1, -1, -1, -1,  1/
    data (nhel(ihel,211),ihel=1,8) /  1,  1, -1,  1, -1, -1,  1, -1/
    data (nhel(ihel,212),ihel=1,8) /  1,  1, -1,  1, -1, -1,  1,  1/
    data (nhel(ihel,213),ihel=1,8) /  1,  1, -1,  1, -1,  1, -1, -1/
    data (nhel(ihel,214),ihel=1,8) /  1,  1, -1,  1, -1,  1, -1,  1/
    data (nhel(ihel,215),ihel=1,8) /  1,  1, -1,  1, -1,  1,  1, -1/
    data (nhel(ihel,216),ihel=1,8) /  1,  1, -1,  1, -1,  1,  1,  1/
    data (nhel(ihel,217),ihel=1,8) /  1,  1, -1,  1,  1, -1, -1, -1/
    data (nhel(ihel,218),ihel=1,8) /  1,  1, -1,  1,  1, -1, -1,  1/
    data (nhel(ihel,219),ihel=1,8) /  1,  1, -1,  1,  1, -1,  1, -1/
    data (nhel(ihel,220),ihel=1,8) /  1,  1, -1,  1,  1, -1,  1,  1/
    data (nhel(ihel,221),ihel=1,8) /  1,  1, -1,  1,  1,  1, -1, -1/
    data (nhel(ihel,222),ihel=1,8) /  1,  1, -1,  1,  1,  1, -1,  1/
    data (nhel(ihel,223),ihel=1,8) /  1,  1, -1,  1,  1,  1,  1, -1/
    data (nhel(ihel,224),ihel=1,8) /  1,  1, -1,  1,  1,  1,  1,  1/
    data (nhel(ihel,225),ihel=1,8) /  1,  1,  1, -1, -1, -1, -1, -1/
    data (nhel(ihel,226),ihel=1,8) /  1,  1,  1, -1, -1, -1, -1,  1/
    data (nhel(ihel,227),ihel=1,8) /  1,  1,  1, -1, -1, -1,  1, -1/
    data (nhel(ihel,228),ihel=1,8) /  1,  1,  1, -1, -1, -1,  1,  1/
    data (nhel(ihel,229),ihel=1,8) /  1,  1,  1, -1, -1,  1, -1, -1/
    data (nhel(ihel,230),ihel=1,8) /  1,  1,  1, -1, -1,  1, -1,  1/
    data (nhel(ihel,231),ihel=1,8) /  1,  1,  1, -1, -1,  1,  1, -1/
    data (nhel(ihel,232),ihel=1,8) /  1,  1,  1, -1, -1,  1,  1,  1/
    data (nhel(ihel,233),ihel=1,8) /  1,  1,  1, -1,  1, -1, -1, -1/
    data (nhel(ihel,234),ihel=1,8) /  1,  1,  1, -1,  1, -1, -1,  1/
    data (nhel(ihel,235),ihel=1,8) /  1,  1,  1, -1,  1, -1,  1, -1/
    data (nhel(ihel,236),ihel=1,8) /  1,  1,  1, -1,  1, -1,  1,  1/
    data (nhel(ihel,237),ihel=1,8) /  1,  1,  1, -1,  1,  1, -1, -1/
    data (nhel(ihel,238),ihel=1,8) /  1,  1,  1, -1,  1,  1, -1,  1/
    data (nhel(ihel,239),ihel=1,8) /  1,  1,  1, -1,  1,  1,  1, -1/
    data (nhel(ihel,240),ihel=1,8) /  1,  1,  1, -1,  1,  1,  1,  1/
    data (nhel(ihel,241),ihel=1,8) /  1,  1,  1,  1, -1, -1, -1, -1/
    data (nhel(ihel,242),ihel=1,8) /  1,  1,  1,  1, -1, -1, -1,  1/
    data (nhel(ihel,243),ihel=1,8) /  1,  1,  1,  1, -1, -1,  1, -1/
    data (nhel(ihel,244),ihel=1,8) /  1,  1,  1,  1, -1, -1,  1,  1/
    data (nhel(ihel,245),ihel=1,8) /  1,  1,  1,  1, -1,  1, -1, -1/
    data (nhel(ihel,246),ihel=1,8) /  1,  1,  1,  1, -1,  1, -1,  1/
    data (nhel(ihel,247),ihel=1,8) /  1,  1,  1,  1, -1,  1,  1, -1/
    data (nhel(ihel,248),ihel=1,8) /  1,  1,  1,  1, -1,  1,  1,  1/
    data (nhel(ihel,249),ihel=1,8) /  1,  1,  1,  1,  1, -1, -1, -1/
    data (nhel(ihel,250),ihel=1,8) /  1,  1,  1,  1,  1, -1, -1,  1/
    data (nhel(ihel,251),ihel=1,8) /  1,  1,  1,  1,  1, -1,  1, -1/
    data (nhel(ihel,252),ihel=1,8) /  1,  1,  1,  1,  1, -1,  1,  1/
    data (nhel(ihel,253),ihel=1,8) /  1,  1,  1,  1,  1,  1, -1, -1/
    data (nhel(ihel,254),ihel=1,8) /  1,  1,  1,  1,  1,  1, -1,  1/
    data (nhel(ihel,255),ihel=1,8) /  1,  1,  1,  1,  1,  1,  1, -1/
    data (nhel(ihel,256),ihel=1,8) /  1,  1,  1,  1,  1,  1,  1,  1/
    ! ----------
    ! begin code
    ! ----------
    sqq_bbtatavtvt = 0d0
    ntry=ntry+1
    do ihel=1,ncomb
        if (goodhel(ihel) .or. ntry < 10) then
            t=qq_bbtatavtvt(p1, p2, p3, p4, p5, p6, p7, p8,nhel(1,ihel))
            sqq_bbtatavtvt = sqq_bbtatavtvt + t
            if (t > 0d0 .and. .not. goodhel(ihel)) then
                goodhel(ihel)= .true.
                write(*,*) ihel,t
            endif
        endif
    enddo
    sqq_bbtatavtvt = sqq_bbtatavtvt /  4d0
end function sqq_bbtatavtvt


function qq_bbtatavtvt(p1, p2, p3, p4, p5, p6, p7, p8,nhel)

    ! function generated by madgraph
    ! returns amplitude squared summed/avg over colors
    ! for the point in phase space p1,p2,p3,p4,...
    ! and helicity nhel(1),nhel(2),....

    ! for process : q q~  -> b b~ e+ e- v v~

    use configuration, only: include_signal, include_background
    use models

    implicit none

    real(kind=default) :: qq_bbtatavtvt

    ! constants

    integer,parameter :: ngraphs = 128, neigen = 1, nexternal = 8
    real, parameter :: zero = 0.d0

    ! arguments

    real(kind=default) :: p1(0:3),p2(0:3),p3(0:3),p4(0:3),p5(0:3),p6(0:3),p7(0:3),p8(0:3)
    integer :: nhel(nexternal)

    ! local variables

    integer :: i,j
    real(kind=default) :: eigen_val(neigen), eigen_vec(ngraphs,neigen)
    complex(kind=complex) ztemp
    complex(kind=complex) amp(ngraphs)
    complex(kind=complex) w1(6)  , w2(6)  , w3(6)  , w4(6)  , w5(6)
    complex(kind=complex) w6(6)  , w7(6)  , w8(6)  , w9(6)  , w10(6)
    complex(kind=complex) w11(6) , w12(6) , w13(6) , w14(6) , w15(6)
    complex(kind=complex) w16(6) , w17(6) , w18(6) , w19(6) , w20(6)
    complex(kind=complex) w21(6) , w22(6) , w23(6) , w24(6) , w25(6)
    complex(kind=complex) w26(6) , w27(6) , w28(6) , w29(6) , w30(6)
    complex(kind=complex) w31(6) , w32(6) , w33(6) , w34(6) , w35(6)
    complex(kind=complex) w36(6) , w37(6) , w38(6) , w39(6) , w40(6)
    complex(kind=complex) w41(6) , w42(6) , w43(6) , w44(6) , w45(6)
    complex(kind=complex) w46(6) , w47(6) , w48(6) , w49(6) , w50(6)
    complex(kind=complex) w51(6) , w52(6) , w53(6) , w54(6) , w55(6)
    complex(kind=complex) w56(6) , w57(6) , w58(6) , w59(6) , w60(6)
    complex(kind=complex) w61(6) , w62(6) , w63(6) , w64(6) , w65(6)
    complex(kind=complex) w66(6) , w67(6) , w68(6) , w69(6) , w70(6)
    complex(kind=complex) w71(6) , w72(6) , w73(6) , w74(6) , w75(6)
    complex(kind=complex) w76(6) , w77(6) , w78(6) , w79(6) , w80(6)
    complex(kind=complex) w81(6) , w82(6) , w83(6) , w84(6) , w85(6)
    complex(kind=complex) w86(6) , w87(6) , w88(6) , w89(6) , w90(6)
    complex(kind=complex) w91(6) , w92(6) , w93(6) , w94(6) , w95(6)
    complex(kind=complex) w96(6) , w97(6) , w98(6) , w99(6) , w100(6)
    complex(kind=complex) w101(6), w102(6), w103(6), w104(6), w105(6)
    complex(kind=complex) w106(6), w107(6), w108(6), w109(6), w110(6)
    complex(kind=complex) w111(6), w112(6), w113(6), w114(6), w115(6)
    complex(kind=complex) w116(6), w117(6), w118(6)

    ! color data

    data eigen_val(1  )/       2.8444444444444446e+01 /
    data eigen_vec(1  ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(2  ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(3  ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(4  ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(5  ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(6  ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(7  ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(8  ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(9  ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(10 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(11 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(12 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(13 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(14 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(15 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(16 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(17 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(18 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(19 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(20 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(21 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(22 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(23 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(24 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(25 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(26 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(27 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(28 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(29 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(30 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(31 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(32 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(33 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(34 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(35 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(36 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(37 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(38 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(39 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(40 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(41 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(42 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(43 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(44 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(45 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(46 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(47 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(48 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(49 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(50 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(51 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(52 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(53 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(54 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(55 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(56 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(57 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(58 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(59 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(60 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(61 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(62 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(63 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(64 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(65 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(66 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(67 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(68 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(69 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(70 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(71 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(72 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(73 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(74 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(75 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(76 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(77 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(78 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(79 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(80 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(81 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(82 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(83 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(84 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(85 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(86 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(87 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(88 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(89 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(90 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(91 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(92 ,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(93 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(94 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(95 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(96 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(97 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(98 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(99 ,1  )/   8.8388347648318433e-02 /
    data eigen_vec(100,1  )/   8.8388347648318433e-02 /
    data eigen_vec(101,1  )/   8.8388347648318433e-02 /
    data eigen_vec(102,1  )/   8.8388347648318433e-02 /
    data eigen_vec(103,1  )/   8.8388347648318433e-02 /
    data eigen_vec(104,1  )/   8.8388347648318433e-02 /
    data eigen_vec(105,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(106,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(107,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(108,1  )/   8.8388347648318433e-02 /
    data eigen_vec(109,1  )/   8.8388347648318433e-02 /
    data eigen_vec(110,1  )/   8.8388347648318433e-02 /
    data eigen_vec(111,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(112,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(113,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(114,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(115,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(116,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(117,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(118,1  )/   8.8388347648318433e-02 /
    data eigen_vec(119,1  )/   8.8388347648318433e-02 /
    data eigen_vec(120,1  )/   8.8388347648318433e-02 /
    data eigen_vec(121,1  )/   8.8388347648318433e-02 /
    data eigen_vec(122,1  )/   8.8388347648318433e-02 /
    data eigen_vec(123,1  )/   8.8388347648318433e-02 /
    data eigen_vec(124,1  )/  -8.8388347648318433e-02 /
    data eigen_vec(125,1  )/   8.8388347648318433e-02 /
    data eigen_vec(126,1  )/   8.8388347648318433e-02 /
    data eigen_vec(127,1  )/   8.8388347648318433e-02 /
    data eigen_vec(128,1  )/   8.8388347648318433e-02 /
    ! ----------
    ! begin code
    ! ----------

    ! initalise amps
    do j = 1, ngraphs
        amp(j) = 0.d0
    end do

    ! wavefunctions
    call ixxxxx(p1  ,zero,nhel(1  ), 1,w1  )
    call oxxxxx(p2  ,zero,nhel(2  ),-1,w2  )
    call oxxxxx(p3  ,fmass(12 ),nhel(3  ), 1,w3  )
    call ixxxxx(p4  ,fmass(12 ),nhel(4  ),-1,w4  )
    call ixxxxx(p5  ,zero,nhel(5  ),-1,w5  )
    call oxxxxx(p6  ,zero,nhel(6  ), 1,w6  )
    call oxxxxx(p7  ,zero,nhel(7  ), 1,w7  )
    call ixxxxx(p8  ,zero,nhel(8  ),-1,w8  )

    call jioxxx(w5  ,w7  ,gwf,wmass,wwidth,w10 )
    call jioxxx(w8  ,w6  ,gwf,wmass,wwidth,w11 )
    call jioxxx(w1  ,w2  ,gg,zero,zero,w55 )
    call fvoxxx(w3  ,w10 ,gwf,fmass(11 ),fwidth(11 ),w56 )
    call fvixxx(w4  ,w11 ,gwf,fmass(11 ),fwidth(11 ),w57 )

    ! currents
    if (include_background == 1) then
      call jioxxx(w4  ,w3  ,gg,zero,zero,w9  )
      call jioxxx(w5  ,w7  ,gwf,wmass,wwidth,w10 )
      call jioxxx(w8  ,w6  ,gwf,wmass,wwidth,w11 )
      call fvixxx(w1  ,w10 ,gwf,fmass(4  ),fwidth(4  ),w12 )
      call fvoxxx(w2  ,w11 ,gwf,fmass(4  ),fwidth(4  ),w13 )
      call jioxxx(w5  ,w6  ,gal,amass,awidth,w14 )
      call jioxxx(w8  ,w7  ,gzn,zmass,zwidth,w15 )
      call fvoxxx(w2  ,w9  ,gg,fmass(3  ),fwidth(3  ),w16 )
      call fvoxxx(w16 ,w14 ,gau,fmass(3  ),fwidth(3  ),w17 )
      call jioxxx(w5  ,w6  ,gzl,zmass,zwidth,w18 )
      call fvoxxx(w16 ,w18 ,gzu,fmass(3  ),fwidth(3  ),w19 )
      call fvixxx(w1  ,w14 ,gau,fmass(3  ),fwidth(3  ),w20 )
      call fvoxxx(w2  ,w15 ,gzu,fmass(3  ),fwidth(3  ),w21 )
      call fvixxx(w1  ,w18 ,gzu,fmass(3  ),fwidth(3  ),w22 )
      call fvoxxx(w3  ,w15 ,gzd,fmass(12 ),fwidth(12 ),w23 )
      call jioxxx(w20 ,w2  ,gg,zero,zero,w24 )
      call jioxxx(w22 ,w2  ,gg,zero,zero,w25 )
      call fvixxx(w4  ,w15 ,gzd,fmass(12 ),fwidth(12 ),w26 )
      call jioxxx(w1  ,w16 ,gau,amass,awidth,w27 )
      call jioxxx(w1  ,w16 ,gzu,zmass,zwidth,w28 )
      call fvoxxx(w6  ,w27 ,gal,fmass(9  ),fwidth(9  ),w29 )
      call fvoxxx(w6  ,w28 ,gzl,fmass(9  ),fwidth(9  ),w30 )
      call fvoxxx(w6  ,w10 ,gwf,fmass(10 ),fwidth(10 ),w31 )
      call fvixxx(w8  ,w10 ,gwf,fmass(9  ),fwidth(9  ),w32 )
      call fvixxx(w5  ,w27 ,gal,fmass(9  ),fwidth(9  ),w33 )
      call fvixxx(w5  ,w28 ,gzl,fmass(9  ),fwidth(9  ),w34 )
      call fvixxx(w5  ,w11 ,gwf,fmass(10 ),fwidth(10 ),w35 )
      call hioxxx(w5  ,w6  ,gchf(1,9  ),hmass,hwidth,w36 )
      call fvixxx(w8  ,w18 ,gzn,fmass(10 ),fwidth(10 ),w37 )
      call fvoxxx(w7  ,w18 ,gzn,fmass(10 ),fwidth(10 ),w38 )
      call jioxxx(w8  ,w38 ,gzn,zmass,zwidth,w39 )
      call fvixxx(w1  ,w9  ,gg,fmass(3  ),fwidth(3  ),w40 )
      call fvixxx(w40 ,w10 ,gwf,fmass(4  ),fwidth(4  ),w41 )
      call fvoxxx(w2  ,w14 ,gau,fmass(3  ),fwidth(3  ),w42 )
      call fvixxx(w1  ,w15 ,gzu,fmass(3  ),fwidth(3  ),w43 )
      call fvoxxx(w2  ,w18 ,gzu,fmass(3  ),fwidth(3  ),w44 )
      call fvixxx(w40 ,w14 ,gau,fmass(3  ),fwidth(3  ),w45 )
      call fvixxx(w40 ,w18 ,gzu,fmass(3  ),fwidth(3  ),w46 )
      call jioxxx(w1  ,w42 ,gg,zero,zero,w47 )
      call jioxxx(w1  ,w44 ,gg,zero,zero,w48 )
      call jioxxx(w40 ,w2  ,gau,amass,awidth,w49 )
      call jioxxx(w40 ,w2  ,gzu,zmass,zwidth,w50 )
      call fvoxxx(w6  ,w49 ,gal,fmass(9  ),fwidth(9  ),w51 )
      call fvoxxx(w6  ,w50 ,gzl,fmass(9  ),fwidth(9  ),w52 )
      call fvixxx(w5  ,w49 ,gal,fmass(9  ),fwidth(9  ),w53 )
      call fvixxx(w5  ,w50 ,gzl,fmass(9  ),fwidth(9  ),w54 )
      call fvoxxx(w3  ,w14 ,gad,fmass(12 ),fwidth(12 ),w58 )
      call jioxxx(w43 ,w2  ,gg,zero,zero,w59 )
      call fvoxxx(w3  ,w18 ,gzd,fmass(12 ),fwidth(12 ),w60 )
      call fsoxxx(w3  ,w36 ,gchf(1,12 ),fmass(12 ),fwidth(12 ),w61 )
      call jioxxx(w1  ,w21 ,gg,zero,zero,w62 )
      call fvixxx(w4  ,w55 ,gg,fmass(12 ),fwidth(12 ),w63 )
      call fvixxx(w63 ,w14 ,gad,fmass(12 ),fwidth(12 ),w64 )
      call fvixxx(w63 ,w18 ,gzd,fmass(12 ),fwidth(12 ),w65 )
      call fsixxx(w63 ,w36 ,gchf(1,12 ),fmass(12 ),fwidth(12 ),w66 )
      call jioxxx(w63 ,w3  ,gad,amass,awidth,w67 )
      call jioxxx(w63 ,w3  ,gzd,zmass,zwidth,w68 )
      call hioxxx(w63 ,w3  ,gchf(1,12 ),hmass,hwidth,w69 )
      call fvoxxx(w6  ,w67 ,gal,fmass(9  ),fwidth(9  ),w70 )
      call jioxxx(w5  ,w70 ,gzl,zmass,zwidth,w71 )
      call fvoxxx(w6  ,w68 ,gzl,fmass(9  ),fwidth(9  ),w72 )
      call jioxxx(w5  ,w72 ,gzl,zmass,zwidth,w73 )
      call fsoxxx(w6  ,w69 ,gchf(1,9  ),fmass(9  ),fwidth(9  ),w74 )
      call jioxxx(w5  ,w74 ,gzl,zmass,zwidth,w75 )
      call fvixxx(w8  ,w68 ,gzn,fmass(10 ),fwidth(10 ),w76 )
      call fvixxx(w5  ,w67 ,gal,fmass(9  ),fwidth(9  ),w77 )
      call jioxxx(w77 ,w7  ,gwf,wmass,wwidth,w78 )
      call fvixxx(w5  ,w68 ,gzl,fmass(9  ),fwidth(9  ),w79 )
      call jioxxx(w79 ,w7  ,gwf,wmass,wwidth,w80 )
      call fsixxx(w5  ,w69 ,gchf(1,9  ),fmass(9  ),fwidth(9  ),w81 )
      call jioxxx(w81 ,w7  ,gwf,wmass,wwidth,w82 )
      call jioxxx(w77 ,w6  ,gzl,zmass,zwidth,w83 )
      call jioxxx(w79 ,w6  ,gzl,zmass,zwidth,w84 )
      call jioxxx(w81 ,w6  ,gzl,zmass,zwidth,w85 )
      call fvoxxx(w7  ,w68 ,gzn,fmass(10 ),fwidth(10 ),w86 )
      call jvsxxx(w68 ,w36 ,gzzh,zmass,zwidth,w87 )
      call jvsxxx(w18 ,w69 ,gzzh,zmass,zwidth,w88 )
      call fvoxxx(w3  ,w55 ,gg,fmass(12 ),fwidth(12 ),w89 )
      call fvoxxx(w89 ,w10 ,gwf,fmass(11 ),fwidth(11 ),w90 )
      call fvixxx(w4  ,w14 ,gad,fmass(12 ),fwidth(12 ),w91 )
      call fvixxx(w4  ,w18 ,gzd,fmass(12 ),fwidth(12 ),w92 )
      call fsixxx(w4  ,w36 ,gchf(1,12 ),fmass(12 ),fwidth(12 ),w93 )
      call fvoxxx(w89 ,w14 ,gad,fmass(12 ),fwidth(12 ),w94 )
      call fvoxxx(w89 ,w18 ,gzd,fmass(12 ),fwidth(12 ),w95 )
      call fsoxxx(w89 ,w36 ,gchf(1,12 ),fmass(12 ),fwidth(12 ),w96 )
      call jioxxx(w4  ,w89 ,gad,amass,awidth,w97 )
      call jioxxx(w4  ,w89 ,gzd,zmass,zwidth,w98 )
      call hioxxx(w4  ,w89 ,gchf(1,12 ),hmass,hwidth,w99 )
      call fvoxxx(w6  ,w97 ,gal,fmass(9  ),fwidth(9  ),w100)
      call jioxxx(w5  ,w100,gzl,zmass,zwidth,w101)
      call fvoxxx(w6  ,w98 ,gzl,fmass(9  ),fwidth(9  ),w102)
      call jioxxx(w5  ,w102,gzl,zmass,zwidth,w103)
      call fsoxxx(w6  ,w99 ,gchf(1,9  ),fmass(9  ),fwidth(9  ),w104)
      call jioxxx(w5  ,w104,gzl,zmass,zwidth,w105)
      call fvixxx(w8  ,w98 ,gzn,fmass(10 ),fwidth(10 ),w106)
      call fvixxx(w5  ,w97 ,gal,fmass(9  ),fwidth(9  ),w107)
      call jioxxx(w107,w7  ,gwf,wmass,wwidth,w108)
      call fvixxx(w5  ,w98 ,gzl,fmass(9  ),fwidth(9  ),w109)
      call jioxxx(w109,w7  ,gwf,wmass,wwidth,w110)
      call fsixxx(w5  ,w99 ,gchf(1,9  ),fmass(9  ),fwidth(9  ),w111)
      call jioxxx(w111,w7  ,gwf,wmass,wwidth,w112)
      call jioxxx(w107,w6  ,gzl,zmass,zwidth,w113)
      call jioxxx(w109,w6  ,gzl,zmass,zwidth,w114)
      call jioxxx(w111,w6  ,gzl,zmass,zwidth,w115)
      call fvoxxx(w7  ,w98 ,gzn,fmass(10 ),fwidth(10 ),w116)
      call jvsxxx(w98 ,w36 ,gzzh,zmass,zwidth,w117)
      call jvsxxx(w18 ,w99 ,gzzh,zmass,zwidth,w118)
    end if
    ! amplitudes
    if (include_signal == 1) then
      call iovxxx(w57 ,w56 ,w55 ,gg,amp(54 ))
    end if

    if (include_background == 1) then
      call iovxxx(w12 ,w13 ,w9  ,gg,amp(1  ))
      call iovxxx(w1  ,w17 ,w15 ,gzu,amp(2  ))
      call iovxxx(w1  ,w19 ,w15 ,gzu,amp(3  ))
      call iovxxx(w20 ,w21 ,w9  ,gg,amp(4  ))
      call iovxxx(w22 ,w21 ,w9  ,gg,amp(5  ))
      call iovxxx(w4  ,w23 ,w24 ,gg,amp(6  ))
      call iovxxx(w4  ,w23 ,w25 ,gg,amp(7  ))
      call iovxxx(w26 ,w3  ,w24 ,gg,amp(8  ))
      call iovxxx(w26 ,w3  ,w25 ,gg,amp(9  ))
      call vvvxxx(w11 ,w10 ,w27 ,gwwa,amp(10 ))
      call vvvxxx(w11 ,w10 ,w28 ,gwwz,amp(11 ))
      call iovxxx(w5  ,w29 ,w15 ,gzl,amp(12 ))
      call iovxxx(w5  ,w30 ,w15 ,gzl,amp(13 ))
      call iovxxx(w8  ,w31 ,w28 ,gzn,amp(14 ))
      call iovxxx(w32 ,w6  ,w27 ,gal,amp(15 ))
      call iovxxx(w32 ,w6  ,w28 ,gzl,amp(16 ))
      call iovxxx(w33 ,w7  ,w11 ,gwf,amp(17 ))
      call iovxxx(w34 ,w7  ,w11 ,gwf,amp(18 ))
      call iovxxx(w33 ,w6  ,w15 ,gzl,amp(19 ))
      call iovxxx(w34 ,w6  ,w15 ,gzl,amp(20 ))
      call iovxxx(w20 ,w16 ,w15 ,gzu,amp(21 ))
      call iovxxx(w22 ,w16 ,w15 ,gzu,amp(22 ))
      call iovxxx(w35 ,w7  ,w28 ,gzn,amp(23 ))
      call vvsxxx(w15 ,w28 ,w36 ,gzzh,amp(24 ))
      call iovxxx(w37 ,w7  ,w28 ,gzn,amp(25 ))
      call iovxxx(w1  ,w16 ,w39 ,gzu,amp(26 ))
      call iovxxx(w12 ,w16 ,w11 ,gwf,amp(27 ))
      call iovxxx(w41 ,w2  ,w11 ,gwf,amp(28 ))
      call iovxxx(w43 ,w42 ,w9  ,gg,amp(29 ))
      call iovxxx(w43 ,w44 ,w9  ,gg,amp(30 ))
      call iovxxx(w45 ,w2  ,w15 ,gzu,amp(31 ))
      call iovxxx(w46 ,w2  ,w15 ,gzu,amp(32 ))
      call iovxxx(w4  ,w23 ,w47 ,gg,amp(33 ))
      call iovxxx(w4  ,w23 ,w48 ,gg,amp(34 ))
      call iovxxx(w26 ,w3  ,w47 ,gg,amp(35 ))
      call iovxxx(w26 ,w3  ,w48 ,gg,amp(36 ))
      call vvvxxx(w11 ,w10 ,w49 ,gwwa,amp(37 ))
      call vvvxxx(w11 ,w10 ,w50 ,gwwz,amp(38 ))
      call iovxxx(w5  ,w51 ,w15 ,gzl,amp(39 ))
      call iovxxx(w5  ,w52 ,w15 ,gzl,amp(40 ))
      call iovxxx(w8  ,w31 ,w50 ,gzn,amp(41 ))
      call iovxxx(w32 ,w6  ,w49 ,gal,amp(42 ))
      call iovxxx(w32 ,w6  ,w50 ,gzl,amp(43 ))
      call iovxxx(w53 ,w7  ,w11 ,gwf,amp(44 ))
      call iovxxx(w54 ,w7  ,w11 ,gwf,amp(45 ))
      call iovxxx(w53 ,w6  ,w15 ,gzl,amp(46 ))
      call iovxxx(w54 ,w6  ,w15 ,gzl,amp(47 ))
      call iovxxx(w40 ,w42 ,w15 ,gzu,amp(48 ))
      call iovxxx(w40 ,w44 ,w15 ,gzu,amp(49 ))
      call iovxxx(w35 ,w7  ,w50 ,gzn,amp(50 ))
      call vvsxxx(w15 ,w50 ,w36 ,gzzh,amp(51 ))
      call iovxxx(w37 ,w7  ,w50 ,gzn,amp(52 ))
      call iovxxx(w40 ,w2  ,w39 ,gzu,amp(53 ))
      call iovxxx(w4  ,w58 ,w59 ,gg,amp(55 ))
      call iovxxx(w4  ,w60 ,w59 ,gg,amp(56 ))
      call iovxxx(w4  ,w61 ,w59 ,gg,amp(57 ))
      call iovxxx(w4  ,w58 ,w62 ,gg,amp(58 ))
      call iovxxx(w4  ,w60 ,w62 ,gg,amp(59 ))
      call iovxxx(w4  ,w61 ,w62 ,gg,amp(60 ))
      call iovxxx(w64 ,w3  ,w15 ,gzd,amp(61 ))
      call iovxxx(w65 ,w3  ,w15 ,gzd,amp(62 ))
      call iovxxx(w66 ,w3  ,w15 ,gzd,amp(63 ))
      call iovxxx(w26 ,w58 ,w55 ,gg,amp(64 ))
      call iovxxx(w26 ,w60 ,w55 ,gg,amp(65 ))
      call iovxxx(w26 ,w61 ,w55 ,gg,amp(66 ))
      call vvvxxx(w11 ,w10 ,w67 ,gwwa,amp(67 ))
      call vvvxxx(w11 ,w10 ,w68 ,gwwz,amp(68 ))
      call vvsxxx(w11 ,w10 ,w69 ,gwwh,amp(69 ))
      call iovxxx(w8  ,w7  ,w71 ,gzn,amp(70 ))
      call iovxxx(w8  ,w7  ,w73 ,gzn,amp(71 ))
      call iovxxx(w8  ,w7  ,w75 ,gzn,amp(72 ))
      call iovxxx(w76 ,w6  ,w10 ,gwf,amp(73 ))
      call iovxxx(w8  ,w70 ,w10 ,gwf,amp(74 ))
      call iovxxx(w8  ,w72 ,w10 ,gwf,amp(75 ))
      call iovxxx(w8  ,w74 ,w10 ,gwf,amp(76 ))
      call iovxxx(w8  ,w6  ,w78 ,gwf,amp(77 ))
      call iovxxx(w8  ,w6  ,w80 ,gwf,amp(78 ))
      call iovxxx(w8  ,w6  ,w82 ,gwf,amp(79 ))
      call iovxxx(w8  ,w7  ,w83 ,gzn,amp(80 ))
      call iovxxx(w8  ,w7  ,w84 ,gzn,amp(81 ))
      call iovxxx(w8  ,w7  ,w85 ,gzn,amp(82 ))
      call iovxxx(w63 ,w58 ,w15 ,gzd,amp(83 ))
      call iovxxx(w63 ,w60 ,w15 ,gzd,amp(84 ))
      call iovxxx(w63 ,w61 ,w15 ,gzd,amp(85 ))
      call iovxxx(w5  ,w86 ,w11 ,gwf,amp(86 ))
      call iovxxx(w8  ,w7  ,w87 ,gzn,amp(87 ))
      call iovxxx(w8  ,w7  ,w88 ,gzn,amp(88 ))
      call iovxxx(w8  ,w86 ,w18 ,gzn,amp(89 ))
      call iovxxx(w8  ,w38 ,w68 ,gzn,amp(90 ))
      call iovxxx(w63 ,w56 ,w11 ,gwf,amp(91 ))
      call iovxxx(w4  ,w90 ,w11 ,gwf,amp(92 ))
      call iovxxx(w91 ,w3  ,w59 ,gg,amp(93 ))
      call iovxxx(w92 ,w3  ,w59 ,gg,amp(94 ))
      call iovxxx(w93 ,w3  ,w59 ,gg,amp(95 ))
      call iovxxx(w91 ,w3  ,w62 ,gg,amp(96 ))
      call iovxxx(w92 ,w3  ,w62 ,gg,amp(97 ))
      call iovxxx(w93 ,w3  ,w62 ,gg,amp(98 ))
      call iovxxx(w91 ,w23 ,w55 ,gg,amp(99 ))
      call iovxxx(w92 ,w23 ,w55 ,gg,amp(100))
      call iovxxx(w93 ,w23 ,w55 ,gg,amp(101))
      call iovxxx(w4  ,w94 ,w15 ,gzd,amp(102))
      call iovxxx(w4  ,w95 ,w15 ,gzd,amp(103))
      call iovxxx(w4  ,w96 ,w15 ,gzd,amp(104))
      call vvvxxx(w11 ,w10 ,w97 ,gwwa,amp(105))
      call vvvxxx(w11 ,w10 ,w98 ,gwwz,amp(106))
      call vvsxxx(w11 ,w10 ,w99 ,gwwh,amp(107))
      call iovxxx(w8  ,w7  ,w101,gzn,amp(108))
      call iovxxx(w8  ,w7  ,w103,gzn,amp(109))
      call iovxxx(w8  ,w7  ,w105,gzn,amp(110))
      call iovxxx(w106,w6  ,w10 ,gwf,amp(111))
      call iovxxx(w8  ,w100,w10 ,gwf,amp(112))
      call iovxxx(w8  ,w102,w10 ,gwf,amp(113))
      call iovxxx(w8  ,w104,w10 ,gwf,amp(114))
      call iovxxx(w8  ,w6  ,w108,gwf,amp(115))
      call iovxxx(w8  ,w6  ,w110,gwf,amp(116))
      call iovxxx(w8  ,w6  ,w112,gwf,amp(117))
      call iovxxx(w8  ,w7  ,w113,gzn,amp(118))
      call iovxxx(w8  ,w7  ,w114,gzn,amp(119))
      call iovxxx(w8  ,w7  ,w115,gzn,amp(120))
      call iovxxx(w91 ,w89 ,w15 ,gzd,amp(121))
      call iovxxx(w92 ,w89 ,w15 ,gzd,amp(122))
      call iovxxx(w93 ,w89 ,w15 ,gzd,amp(123))
      call iovxxx(w5  ,w116,w11 ,gwf,amp(124))
      call iovxxx(w8  ,w7  ,w117,gzn,amp(125))
      call iovxxx(w8  ,w7  ,w118,gzn,amp(126))
      call iovxxx(w8  ,w116,w18 ,gzn,amp(127))
      call iovxxx(w8  ,w38 ,w98 ,gzn,amp(128))
    end if

    qq_bbtatavtvt = 0.d0
    do i = 1, neigen
        ztemp = (0.d0,0.d0)
        do j = 1, ngraphs
            ztemp = ztemp + eigen_vec(j,i)*amp(j)
        enddo
        qq_bbtatavtvt =qq_bbtatavtvt+ztemp*eigen_val(i)*conjg(ztemp)
    enddo
    !      call gaugecheck(amp,ztemp,eigen_vec,eigen_val,ngraphs,neigen)
end function qq_bbtatavtvt
