function sqq_bbemuvevm(p1, p2, p3, p4, p5, p6, p7, p8)

    ! function generated by madgraph
    ! returns amplitude squared summed/avg over colors
    ! and helicities
    ! for the point in phase space p1, p2, p3, p4,...

    ! for process : q q~  -> b b~ e+ mu- ve vm~

    implicit none

    real*8 :: sqq_bbemuvevm

    ! constants
    integer, parameter :: nexternal = 8, ncomb = 256

    ! arguments
    real*8 :: p1(0:3),p2(0:3),p3(0:3),p4(0:3),p5(0:3),p6(0:3),p7(0:3),p8(0:3)

    ! local variables
    integer :: nhel(nexternal, ncomb), ntry
    real*8 :: t
    real*8 :: qq_bbemuvevm
    integer :: ihel
    logical :: goodhel(ncomb)
    data goodhel/ncomb* .FALSE. /
    data ntry/0/
    data (nhel(ihel,  1),ihel=1,8) / -1, -1, -1, -1, -1, -1, -1, -1/
    data (nhel(ihel,  2),ihel=1,8) / -1, -1, -1, -1, -1, -1, -1,  1/
    data (nhel(ihel,  3),ihel=1,8) / -1, -1, -1, -1, -1, -1,  1, -1/
    data (nhel(ihel,  4),ihel=1,8) / -1, -1, -1, -1, -1, -1,  1,  1/
    data (nhel(ihel,  5),ihel=1,8) / -1, -1, -1, -1, -1,  1, -1, -1/
    data (nhel(ihel,  6),ihel=1,8) / -1, -1, -1, -1, -1,  1, -1,  1/
    data (nhel(ihel,  7),ihel=1,8) / -1, -1, -1, -1, -1,  1,  1, -1/
    data (nhel(ihel,  8),ihel=1,8) / -1, -1, -1, -1, -1,  1,  1,  1/
    data (nhel(ihel,  9),ihel=1,8) / -1, -1, -1, -1,  1, -1, -1, -1/
    data (nhel(ihel, 10),ihel=1,8) / -1, -1, -1, -1,  1, -1, -1,  1/
    data (nhel(ihel, 11),ihel=1,8) / -1, -1, -1, -1,  1, -1,  1, -1/
    data (nhel(ihel, 12),ihel=1,8) / -1, -1, -1, -1,  1, -1,  1,  1/
    data (nhel(ihel, 13),ihel=1,8) / -1, -1, -1, -1,  1,  1, -1, -1/
    data (nhel(ihel, 14),ihel=1,8) / -1, -1, -1, -1,  1,  1, -1,  1/
    data (nhel(ihel, 15),ihel=1,8) / -1, -1, -1, -1,  1,  1,  1, -1/
    data (nhel(ihel, 16),ihel=1,8) / -1, -1, -1, -1,  1,  1,  1,  1/
    data (nhel(ihel, 17),ihel=1,8) / -1, -1, -1,  1, -1, -1, -1, -1/
    data (nhel(ihel, 18),ihel=1,8) / -1, -1, -1,  1, -1, -1, -1,  1/
    data (nhel(ihel, 19),ihel=1,8) / -1, -1, -1,  1, -1, -1,  1, -1/
    data (nhel(ihel, 20),ihel=1,8) / -1, -1, -1,  1, -1, -1,  1,  1/
    data (nhel(ihel, 21),ihel=1,8) / -1, -1, -1,  1, -1,  1, -1, -1/
    data (nhel(ihel, 22),ihel=1,8) / -1, -1, -1,  1, -1,  1, -1,  1/
    data (nhel(ihel, 23),ihel=1,8) / -1, -1, -1,  1, -1,  1,  1, -1/
    data (nhel(ihel, 24),ihel=1,8) / -1, -1, -1,  1, -1,  1,  1,  1/
    data (nhel(ihel, 25),ihel=1,8) / -1, -1, -1,  1,  1, -1, -1, -1/
    data (nhel(ihel, 26),ihel=1,8) / -1, -1, -1,  1,  1, -1, -1,  1/
    data (nhel(ihel, 27),ihel=1,8) / -1, -1, -1,  1,  1, -1,  1, -1/
    data (nhel(ihel, 28),ihel=1,8) / -1, -1, -1,  1,  1, -1,  1,  1/
    data (nhel(ihel, 29),ihel=1,8) / -1, -1, -1,  1,  1,  1, -1, -1/
    data (nhel(ihel, 30),ihel=1,8) / -1, -1, -1,  1,  1,  1, -1,  1/
    data (nhel(ihel, 31),ihel=1,8) / -1, -1, -1,  1,  1,  1,  1, -1/
    data (nhel(ihel, 32),ihel=1,8) / -1, -1, -1,  1,  1,  1,  1,  1/
    data (nhel(ihel, 33),ihel=1,8) / -1, -1,  1, -1, -1, -1, -1, -1/
    data (nhel(ihel, 34),ihel=1,8) / -1, -1,  1, -1, -1, -1, -1,  1/
    data (nhel(ihel, 35),ihel=1,8) / -1, -1,  1, -1, -1, -1,  1, -1/
    data (nhel(ihel, 36),ihel=1,8) / -1, -1,  1, -1, -1, -1,  1,  1/
    data (nhel(ihel, 37),ihel=1,8) / -1, -1,  1, -1, -1,  1, -1, -1/
    data (nhel(ihel, 38),ihel=1,8) / -1, -1,  1, -1, -1,  1, -1,  1/
    data (nhel(ihel, 39),ihel=1,8) / -1, -1,  1, -1, -1,  1,  1, -1/
    data (nhel(ihel, 40),ihel=1,8) / -1, -1,  1, -1, -1,  1,  1,  1/
    data (nhel(ihel, 41),ihel=1,8) / -1, -1,  1, -1,  1, -1, -1, -1/
    data (nhel(ihel, 42),ihel=1,8) / -1, -1,  1, -1,  1, -1, -1,  1/
    data (nhel(ihel, 43),ihel=1,8) / -1, -1,  1, -1,  1, -1,  1, -1/
    data (nhel(ihel, 44),ihel=1,8) / -1, -1,  1, -1,  1, -1,  1,  1/
    data (nhel(ihel, 45),ihel=1,8) / -1, -1,  1, -1,  1,  1, -1, -1/
    data (nhel(ihel, 46),ihel=1,8) / -1, -1,  1, -1,  1,  1, -1,  1/
    data (nhel(ihel, 47),ihel=1,8) / -1, -1,  1, -1,  1,  1,  1, -1/
    data (nhel(ihel, 48),ihel=1,8) / -1, -1,  1, -1,  1,  1,  1,  1/
    data (nhel(ihel, 49),ihel=1,8) / -1, -1,  1,  1, -1, -1, -1, -1/
    data (nhel(ihel, 50),ihel=1,8) / -1, -1,  1,  1, -1, -1, -1,  1/
    data (nhel(ihel, 51),ihel=1,8) / -1, -1,  1,  1, -1, -1,  1, -1/
    data (nhel(ihel, 52),ihel=1,8) / -1, -1,  1,  1, -1, -1,  1,  1/
    data (nhel(ihel, 53),ihel=1,8) / -1, -1,  1,  1, -1,  1, -1, -1/
    data (nhel(ihel, 54),ihel=1,8) / -1, -1,  1,  1, -1,  1, -1,  1/
    data (nhel(ihel, 55),ihel=1,8) / -1, -1,  1,  1, -1,  1,  1, -1/
    data (nhel(ihel, 56),ihel=1,8) / -1, -1,  1,  1, -1,  1,  1,  1/
    data (nhel(ihel, 57),ihel=1,8) / -1, -1,  1,  1,  1, -1, -1, -1/
    data (nhel(ihel, 58),ihel=1,8) / -1, -1,  1,  1,  1, -1, -1,  1/
    data (nhel(ihel, 59),ihel=1,8) / -1, -1,  1,  1,  1, -1,  1, -1/
    data (nhel(ihel, 60),ihel=1,8) / -1, -1,  1,  1,  1, -1,  1,  1/
    data (nhel(ihel, 61),ihel=1,8) / -1, -1,  1,  1,  1,  1, -1, -1/
    data (nhel(ihel, 62),ihel=1,8) / -1, -1,  1,  1,  1,  1, -1,  1/
    data (nhel(ihel, 63),ihel=1,8) / -1, -1,  1,  1,  1,  1,  1, -1/
    data (nhel(ihel, 64),ihel=1,8) / -1, -1,  1,  1,  1,  1,  1,  1/
    data (nhel(ihel, 65),ihel=1,8) / -1,  1, -1, -1, -1, -1, -1, -1/
    data (nhel(ihel, 66),ihel=1,8) / -1,  1, -1, -1, -1, -1, -1,  1/
    data (nhel(ihel, 67),ihel=1,8) / -1,  1, -1, -1, -1, -1,  1, -1/
    data (nhel(ihel, 68),ihel=1,8) / -1,  1, -1, -1, -1, -1,  1,  1/
    data (nhel(ihel, 69),ihel=1,8) / -1,  1, -1, -1, -1,  1, -1, -1/
    data (nhel(ihel, 70),ihel=1,8) / -1,  1, -1, -1, -1,  1, -1,  1/
    data (nhel(ihel, 71),ihel=1,8) / -1,  1, -1, -1, -1,  1,  1, -1/
    data (nhel(ihel, 72),ihel=1,8) / -1,  1, -1, -1, -1,  1,  1,  1/
    data (nhel(ihel, 73),ihel=1,8) / -1,  1, -1, -1,  1, -1, -1, -1/
    data (nhel(ihel, 74),ihel=1,8) / -1,  1, -1, -1,  1, -1, -1,  1/
    data (nhel(ihel, 75),ihel=1,8) / -1,  1, -1, -1,  1, -1,  1, -1/
    data (nhel(ihel, 76),ihel=1,8) / -1,  1, -1, -1,  1, -1,  1,  1/
    data (nhel(ihel, 77),ihel=1,8) / -1,  1, -1, -1,  1,  1, -1, -1/
    data (nhel(ihel, 78),ihel=1,8) / -1,  1, -1, -1,  1,  1, -1,  1/
    data (nhel(ihel, 79),ihel=1,8) / -1,  1, -1, -1,  1,  1,  1, -1/
    data (nhel(ihel, 80),ihel=1,8) / -1,  1, -1, -1,  1,  1,  1,  1/
    data (nhel(ihel, 81),ihel=1,8) / -1,  1, -1,  1, -1, -1, -1, -1/
    data (nhel(ihel, 82),ihel=1,8) / -1,  1, -1,  1, -1, -1, -1,  1/
    data (nhel(ihel, 83),ihel=1,8) / -1,  1, -1,  1, -1, -1,  1, -1/
    data (nhel(ihel, 84),ihel=1,8) / -1,  1, -1,  1, -1, -1,  1,  1/
    data (nhel(ihel, 85),ihel=1,8) / -1,  1, -1,  1, -1,  1, -1, -1/
    data (nhel(ihel, 86),ihel=1,8) / -1,  1, -1,  1, -1,  1, -1,  1/
    data (nhel(ihel, 87),ihel=1,8) / -1,  1, -1,  1, -1,  1,  1, -1/
    data (nhel(ihel, 88),ihel=1,8) / -1,  1, -1,  1, -1,  1,  1,  1/
    data (nhel(ihel, 89),ihel=1,8) / -1,  1, -1,  1,  1, -1, -1, -1/
    data (nhel(ihel, 90),ihel=1,8) / -1,  1, -1,  1,  1, -1, -1,  1/
    data (nhel(ihel, 91),ihel=1,8) / -1,  1, -1,  1,  1, -1,  1, -1/
    data (nhel(ihel, 92),ihel=1,8) / -1,  1, -1,  1,  1, -1,  1,  1/
    data (nhel(ihel, 93),ihel=1,8) / -1,  1, -1,  1,  1,  1, -1, -1/
    data (nhel(ihel, 94),ihel=1,8) / -1,  1, -1,  1,  1,  1, -1,  1/
    data (nhel(ihel, 95),ihel=1,8) / -1,  1, -1,  1,  1,  1,  1, -1/
    data (nhel(ihel, 96),ihel=1,8) / -1,  1, -1,  1,  1,  1,  1,  1/
    data (nhel(ihel, 97),ihel=1,8) / -1,  1,  1, -1, -1, -1, -1, -1/
    data (nhel(ihel, 98),ihel=1,8) / -1,  1,  1, -1, -1, -1, -1,  1/
    data (nhel(ihel, 99),ihel=1,8) / -1,  1,  1, -1, -1, -1,  1, -1/
    data (nhel(ihel,100),ihel=1,8) / -1,  1,  1, -1, -1, -1,  1,  1/
    data (nhel(ihel,101),ihel=1,8) / -1,  1,  1, -1, -1,  1, -1, -1/
    data (nhel(ihel,102),ihel=1,8) / -1,  1,  1, -1, -1,  1, -1,  1/
    data (nhel(ihel,103),ihel=1,8) / -1,  1,  1, -1, -1,  1,  1, -1/
    data (nhel(ihel,104),ihel=1,8) / -1,  1,  1, -1, -1,  1,  1,  1/
    data (nhel(ihel,105),ihel=1,8) / -1,  1,  1, -1,  1, -1, -1, -1/
    data (nhel(ihel,106),ihel=1,8) / -1,  1,  1, -1,  1, -1, -1,  1/
    data (nhel(ihel,107),ihel=1,8) / -1,  1,  1, -1,  1, -1,  1, -1/
    data (nhel(ihel,108),ihel=1,8) / -1,  1,  1, -1,  1, -1,  1,  1/
    data (nhel(ihel,109),ihel=1,8) / -1,  1,  1, -1,  1,  1, -1, -1/
    data (nhel(ihel,110),ihel=1,8) / -1,  1,  1, -1,  1,  1, -1,  1/
    data (nhel(ihel,111),ihel=1,8) / -1,  1,  1, -1,  1,  1,  1, -1/
    data (nhel(ihel,112),ihel=1,8) / -1,  1,  1, -1,  1,  1,  1,  1/
    data (nhel(ihel,113),ihel=1,8) / -1,  1,  1,  1, -1, -1, -1, -1/
    data (nhel(ihel,114),ihel=1,8) / -1,  1,  1,  1, -1, -1, -1,  1/
    data (nhel(ihel,115),ihel=1,8) / -1,  1,  1,  1, -1, -1,  1, -1/
    data (nhel(ihel,116),ihel=1,8) / -1,  1,  1,  1, -1, -1,  1,  1/
    data (nhel(ihel,117),ihel=1,8) / -1,  1,  1,  1, -1,  1, -1, -1/
    data (nhel(ihel,118),ihel=1,8) / -1,  1,  1,  1, -1,  1, -1,  1/
    data (nhel(ihel,119),ihel=1,8) / -1,  1,  1,  1, -1,  1,  1, -1/
    data (nhel(ihel,120),ihel=1,8) / -1,  1,  1,  1, -1,  1,  1,  1/
    data (nhel(ihel,121),ihel=1,8) / -1,  1,  1,  1,  1, -1, -1, -1/
    data (nhel(ihel,122),ihel=1,8) / -1,  1,  1,  1,  1, -1, -1,  1/
    data (nhel(ihel,123),ihel=1,8) / -1,  1,  1,  1,  1, -1,  1, -1/
    data (nhel(ihel,124),ihel=1,8) / -1,  1,  1,  1,  1, -1,  1,  1/
    data (nhel(ihel,125),ihel=1,8) / -1,  1,  1,  1,  1,  1, -1, -1/
    data (nhel(ihel,126),ihel=1,8) / -1,  1,  1,  1,  1,  1, -1,  1/
    data (nhel(ihel,127),ihel=1,8) / -1,  1,  1,  1,  1,  1,  1, -1/
    data (nhel(ihel,128),ihel=1,8) / -1,  1,  1,  1,  1,  1,  1,  1/
    data (nhel(ihel,129),ihel=1,8) /  1, -1, -1, -1, -1, -1, -1, -1/
    data (nhel(ihel,130),ihel=1,8) /  1, -1, -1, -1, -1, -1, -1,  1/
    data (nhel(ihel,131),ihel=1,8) /  1, -1, -1, -1, -1, -1,  1, -1/
    data (nhel(ihel,132),ihel=1,8) /  1, -1, -1, -1, -1, -1,  1,  1/
    data (nhel(ihel,133),ihel=1,8) /  1, -1, -1, -1, -1,  1, -1, -1/
    data (nhel(ihel,134),ihel=1,8) /  1, -1, -1, -1, -1,  1, -1,  1/
    data (nhel(ihel,135),ihel=1,8) /  1, -1, -1, -1, -1,  1,  1, -1/
    data (nhel(ihel,136),ihel=1,8) /  1, -1, -1, -1, -1,  1,  1,  1/
    data (nhel(ihel,137),ihel=1,8) /  1, -1, -1, -1,  1, -1, -1, -1/
    data (nhel(ihel,138),ihel=1,8) /  1, -1, -1, -1,  1, -1, -1,  1/
    data (nhel(ihel,139),ihel=1,8) /  1, -1, -1, -1,  1, -1,  1, -1/
    data (nhel(ihel,140),ihel=1,8) /  1, -1, -1, -1,  1, -1,  1,  1/
    data (nhel(ihel,141),ihel=1,8) /  1, -1, -1, -1,  1,  1, -1, -1/
    data (nhel(ihel,142),ihel=1,8) /  1, -1, -1, -1,  1,  1, -1,  1/
    data (nhel(ihel,143),ihel=1,8) /  1, -1, -1, -1,  1,  1,  1, -1/
    data (nhel(ihel,144),ihel=1,8) /  1, -1, -1, -1,  1,  1,  1,  1/
    data (nhel(ihel,145),ihel=1,8) /  1, -1, -1,  1, -1, -1, -1, -1/
    data (nhel(ihel,146),ihel=1,8) /  1, -1, -1,  1, -1, -1, -1,  1/
    data (nhel(ihel,147),ihel=1,8) /  1, -1, -1,  1, -1, -1,  1, -1/
    data (nhel(ihel,148),ihel=1,8) /  1, -1, -1,  1, -1, -1,  1,  1/
    data (nhel(ihel,149),ihel=1,8) /  1, -1, -1,  1, -1,  1, -1, -1/
    data (nhel(ihel,150),ihel=1,8) /  1, -1, -1,  1, -1,  1, -1,  1/
    data (nhel(ihel,151),ihel=1,8) /  1, -1, -1,  1, -1,  1,  1, -1/
    data (nhel(ihel,152),ihel=1,8) /  1, -1, -1,  1, -1,  1,  1,  1/
    data (nhel(ihel,153),ihel=1,8) /  1, -1, -1,  1,  1, -1, -1, -1/
    data (nhel(ihel,154),ihel=1,8) /  1, -1, -1,  1,  1, -1, -1,  1/
    data (nhel(ihel,155),ihel=1,8) /  1, -1, -1,  1,  1, -1,  1, -1/
    data (nhel(ihel,156),ihel=1,8) /  1, -1, -1,  1,  1, -1,  1,  1/
    data (nhel(ihel,157),ihel=1,8) /  1, -1, -1,  1,  1,  1, -1, -1/
    data (nhel(ihel,158),ihel=1,8) /  1, -1, -1,  1,  1,  1, -1,  1/
    data (nhel(ihel,159),ihel=1,8) /  1, -1, -1,  1,  1,  1,  1, -1/
    data (nhel(ihel,160),ihel=1,8) /  1, -1, -1,  1,  1,  1,  1,  1/
    data (nhel(ihel,161),ihel=1,8) /  1, -1,  1, -1, -1, -1, -1, -1/
    data (nhel(ihel,162),ihel=1,8) /  1, -1,  1, -1, -1, -1, -1,  1/
    data (nhel(ihel,163),ihel=1,8) /  1, -1,  1, -1, -1, -1,  1, -1/
    data (nhel(ihel,164),ihel=1,8) /  1, -1,  1, -1, -1, -1,  1,  1/
    data (nhel(ihel,165),ihel=1,8) /  1, -1,  1, -1, -1,  1, -1, -1/
    data (nhel(ihel,166),ihel=1,8) /  1, -1,  1, -1, -1,  1, -1,  1/
    data (nhel(ihel,167),ihel=1,8) /  1, -1,  1, -1, -1,  1,  1, -1/
    data (nhel(ihel,168),ihel=1,8) /  1, -1,  1, -1, -1,  1,  1,  1/
    data (nhel(ihel,169),ihel=1,8) /  1, -1,  1, -1,  1, -1, -1, -1/
    data (nhel(ihel,170),ihel=1,8) /  1, -1,  1, -1,  1, -1, -1,  1/
    data (nhel(ihel,171),ihel=1,8) /  1, -1,  1, -1,  1, -1,  1, -1/
    data (nhel(ihel,172),ihel=1,8) /  1, -1,  1, -1,  1, -1,  1,  1/
    data (nhel(ihel,173),ihel=1,8) /  1, -1,  1, -1,  1,  1, -1, -1/
    data (nhel(ihel,174),ihel=1,8) /  1, -1,  1, -1,  1,  1, -1,  1/
    data (nhel(ihel,175),ihel=1,8) /  1, -1,  1, -1,  1,  1,  1, -1/
    data (nhel(ihel,176),ihel=1,8) /  1, -1,  1, -1,  1,  1,  1,  1/
    data (nhel(ihel,177),ihel=1,8) /  1, -1,  1,  1, -1, -1, -1, -1/
    data (nhel(ihel,178),ihel=1,8) /  1, -1,  1,  1, -1, -1, -1,  1/
    data (nhel(ihel,179),ihel=1,8) /  1, -1,  1,  1, -1, -1,  1, -1/
    data (nhel(ihel,180),ihel=1,8) /  1, -1,  1,  1, -1, -1,  1,  1/
    data (nhel(ihel,181),ihel=1,8) /  1, -1,  1,  1, -1,  1, -1, -1/
    data (nhel(ihel,182),ihel=1,8) /  1, -1,  1,  1, -1,  1, -1,  1/
    data (nhel(ihel,183),ihel=1,8) /  1, -1,  1,  1, -1,  1,  1, -1/
    data (nhel(ihel,184),ihel=1,8) /  1, -1,  1,  1, -1,  1,  1,  1/
    data (nhel(ihel,185),ihel=1,8) /  1, -1,  1,  1,  1, -1, -1, -1/
    data (nhel(ihel,186),ihel=1,8) /  1, -1,  1,  1,  1, -1, -1,  1/
    data (nhel(ihel,187),ihel=1,8) /  1, -1,  1,  1,  1, -1,  1, -1/
    data (nhel(ihel,188),ihel=1,8) /  1, -1,  1,  1,  1, -1,  1,  1/
    data (nhel(ihel,189),ihel=1,8) /  1, -1,  1,  1,  1,  1, -1, -1/
    data (nhel(ihel,190),ihel=1,8) /  1, -1,  1,  1,  1,  1, -1,  1/
    data (nhel(ihel,191),ihel=1,8) /  1, -1,  1,  1,  1,  1,  1, -1/
    data (nhel(ihel,192),ihel=1,8) /  1, -1,  1,  1,  1,  1,  1,  1/
    data (nhel(ihel,193),ihel=1,8) /  1,  1, -1, -1, -1, -1, -1, -1/
    data (nhel(ihel,194),ihel=1,8) /  1,  1, -1, -1, -1, -1, -1,  1/
    data (nhel(ihel,195),ihel=1,8) /  1,  1, -1, -1, -1, -1,  1, -1/
    data (nhel(ihel,196),ihel=1,8) /  1,  1, -1, -1, -1, -1,  1,  1/
    data (nhel(ihel,197),ihel=1,8) /  1,  1, -1, -1, -1,  1, -1, -1/
    data (nhel(ihel,198),ihel=1,8) /  1,  1, -1, -1, -1,  1, -1,  1/
    data (nhel(ihel,199),ihel=1,8) /  1,  1, -1, -1, -1,  1,  1, -1/
    data (nhel(ihel,200),ihel=1,8) /  1,  1, -1, -1, -1,  1,  1,  1/
    data (nhel(ihel,201),ihel=1,8) /  1,  1, -1, -1,  1, -1, -1, -1/
    data (nhel(ihel,202),ihel=1,8) /  1,  1, -1, -1,  1, -1, -1,  1/
    data (nhel(ihel,203),ihel=1,8) /  1,  1, -1, -1,  1, -1,  1, -1/
    data (nhel(ihel,204),ihel=1,8) /  1,  1, -1, -1,  1, -1,  1,  1/
    data (nhel(ihel,205),ihel=1,8) /  1,  1, -1, -1,  1,  1, -1, -1/
    data (nhel(ihel,206),ihel=1,8) /  1,  1, -1, -1,  1,  1, -1,  1/
    data (nhel(ihel,207),ihel=1,8) /  1,  1, -1, -1,  1,  1,  1, -1/
    data (nhel(ihel,208),ihel=1,8) /  1,  1, -1, -1,  1,  1,  1,  1/
    data (nhel(ihel,209),ihel=1,8) /  1,  1, -1,  1, -1, -1, -1, -1/
    data (nhel(ihel,210),ihel=1,8) /  1,  1, -1,  1, -1, -1, -1,  1/
    data (nhel(ihel,211),ihel=1,8) /  1,  1, -1,  1, -1, -1,  1, -1/
    data (nhel(ihel,212),ihel=1,8) /  1,  1, -1,  1, -1, -1,  1,  1/
    data (nhel(ihel,213),ihel=1,8) /  1,  1, -1,  1, -1,  1, -1, -1/
    data (nhel(ihel,214),ihel=1,8) /  1,  1, -1,  1, -1,  1, -1,  1/
    data (nhel(ihel,215),ihel=1,8) /  1,  1, -1,  1, -1,  1,  1, -1/
    data (nhel(ihel,216),ihel=1,8) /  1,  1, -1,  1, -1,  1,  1,  1/
    data (nhel(ihel,217),ihel=1,8) /  1,  1, -1,  1,  1, -1, -1, -1/
    data (nhel(ihel,218),ihel=1,8) /  1,  1, -1,  1,  1, -1, -1,  1/
    data (nhel(ihel,219),ihel=1,8) /  1,  1, -1,  1,  1, -1,  1, -1/
    data (nhel(ihel,220),ihel=1,8) /  1,  1, -1,  1,  1, -1,  1,  1/
    data (nhel(ihel,221),ihel=1,8) /  1,  1, -1,  1,  1,  1, -1, -1/
    data (nhel(ihel,222),ihel=1,8) /  1,  1, -1,  1,  1,  1, -1,  1/
    data (nhel(ihel,223),ihel=1,8) /  1,  1, -1,  1,  1,  1,  1, -1/
    data (nhel(ihel,224),ihel=1,8) /  1,  1, -1,  1,  1,  1,  1,  1/
    data (nhel(ihel,225),ihel=1,8) /  1,  1,  1, -1, -1, -1, -1, -1/
    data (nhel(ihel,226),ihel=1,8) /  1,  1,  1, -1, -1, -1, -1,  1/
    data (nhel(ihel,227),ihel=1,8) /  1,  1,  1, -1, -1, -1,  1, -1/
    data (nhel(ihel,228),ihel=1,8) /  1,  1,  1, -1, -1, -1,  1,  1/
    data (nhel(ihel,229),ihel=1,8) /  1,  1,  1, -1, -1,  1, -1, -1/
    data (nhel(ihel,230),ihel=1,8) /  1,  1,  1, -1, -1,  1, -1,  1/
    data (nhel(ihel,231),ihel=1,8) /  1,  1,  1, -1, -1,  1,  1, -1/
    data (nhel(ihel,232),ihel=1,8) /  1,  1,  1, -1, -1,  1,  1,  1/
    data (nhel(ihel,233),ihel=1,8) /  1,  1,  1, -1,  1, -1, -1, -1/
    data (nhel(ihel,234),ihel=1,8) /  1,  1,  1, -1,  1, -1, -1,  1/
    data (nhel(ihel,235),ihel=1,8) /  1,  1,  1, -1,  1, -1,  1, -1/
    data (nhel(ihel,236),ihel=1,8) /  1,  1,  1, -1,  1, -1,  1,  1/
    data (nhel(ihel,237),ihel=1,8) /  1,  1,  1, -1,  1,  1, -1, -1/
    data (nhel(ihel,238),ihel=1,8) /  1,  1,  1, -1,  1,  1, -1,  1/
    data (nhel(ihel,239),ihel=1,8) /  1,  1,  1, -1,  1,  1,  1, -1/
    data (nhel(ihel,240),ihel=1,8) /  1,  1,  1, -1,  1,  1,  1,  1/
    data (nhel(ihel,241),ihel=1,8) /  1,  1,  1,  1, -1, -1, -1, -1/
    data (nhel(ihel,242),ihel=1,8) /  1,  1,  1,  1, -1, -1, -1,  1/
    data (nhel(ihel,243),ihel=1,8) /  1,  1,  1,  1, -1, -1,  1, -1/
    data (nhel(ihel,244),ihel=1,8) /  1,  1,  1,  1, -1, -1,  1,  1/
    data (nhel(ihel,245),ihel=1,8) /  1,  1,  1,  1, -1,  1, -1, -1/
    data (nhel(ihel,246),ihel=1,8) /  1,  1,  1,  1, -1,  1, -1,  1/
    data (nhel(ihel,247),ihel=1,8) /  1,  1,  1,  1, -1,  1,  1, -1/
    data (nhel(ihel,248),ihel=1,8) /  1,  1,  1,  1, -1,  1,  1,  1/
    data (nhel(ihel,249),ihel=1,8) /  1,  1,  1,  1,  1, -1, -1, -1/
    data (nhel(ihel,250),ihel=1,8) /  1,  1,  1,  1,  1, -1, -1,  1/
    data (nhel(ihel,251),ihel=1,8) /  1,  1,  1,  1,  1, -1,  1, -1/
    data (nhel(ihel,252),ihel=1,8) /  1,  1,  1,  1,  1, -1,  1,  1/
    data (nhel(ihel,253),ihel=1,8) /  1,  1,  1,  1,  1,  1, -1, -1/
    data (nhel(ihel,254),ihel=1,8) /  1,  1,  1,  1,  1,  1, -1,  1/
    data (nhel(ihel,255),ihel=1,8) /  1,  1,  1,  1,  1,  1,  1, -1/
    data (nhel(ihel,256),ihel=1,8) /  1,  1,  1,  1,  1,  1,  1,  1/
    ! ----------
    ! begin code
    ! ----------
    sqq_bbemuvevm = 0d0
    ntry = ntry + 1
    do ihel = 1, ncomb
        if (goodhel(ihel) .or. ntry < 10) then
            t = qq_bbemuvevm(p1, p2, p3, p4, p5, p6, p7, p8, nhel(1, ihel))
            sqq_bbemuvevm = sqq_bbemuvevm + t
            if (t > 0d0 .and. .not. goodhel(ihel)) then
                goodhel(ihel) = .true.
                ! write(*,*) ihel,t
            endif
        endif
    enddo
    sqq_bbemuvevm = sqq_bbemuvevm/4d0
end function sqq_bbemuvevm


function qq_bbemuvevm(p1, p2, p3, p4, p5, p6, p7, p8,nhel)

    ! function generated by madgraph
    ! returns amplitude squared summed/avg over colors
    ! for the point in phase space p1,p2,p3,p4,...
    ! and helicity nhel(1),nhel(2),....

    ! for process : u u~  -> b b~ e+ mu- ve vm~

    use modelling
    use configuration, only: include_signal, include_background

    implicit none

    real*8 :: qq_bbemuvevm

    ! constants
    integer, parameter :: ngraphs = 44, neigen = 1, nexternal = 8
    real*8, parameter :: zero = 0d0

    ! arguments
    real*8 :: p1(0:3), p2(0:3), p3(0:3), p4(0:3), p5(0:3), p6(0:3), p7(0:3), p8(0:3)
    integer :: nhel(nexternal)

    ! variables
    integer :: i, j
    real*8 :: eigen_val(neigen), eigen_vec(ngraphs, neigen)
    complex*16 ztemp
    complex*16 amp(ngraphs)
    complex*16 w1(6) ,  w2(6) ,  w3(6) ,  w4(6) ,  w5(6)
    complex*16 w6(6) ,  w7(6) ,  w8(6) ,  w9(6) ,  w10(6)
    complex*16 w11(6),  w12(6),  w13(6),  w14(6),  w15(6)
    complex*16 w16(6),  w17(6),  w18(6),  w19(6),  w20(6)
    complex*16 w21(6),  w22(6),  w23(6),  w24(6),  w25(6)
    complex*16 w26(6),  w27(6),  w28(6),  w29(6),  w30(6)
    complex*16 w31(6),  w32(6),  w33(6),  w34(6),  w35(6)
    complex*16 w36(6),  w37(6),  w38(6),  w39(6),  w40(6)
    complex*16 w41(6),  w42(6),  w43(6),  w44(6),  w45(6)
    complex*16 w46(6),  w47(6),  w48(6),  w49(6),  w50(6)
    complex*16 w51(6),  w52(6),  w53(6),  w54(6),  w55(6)
    complex*16 w56(6),  w57(6),  w58(6),  w59(6)

    ! color data
    data eigen_val(1) /9.7777777777777768e+00/
    data eigen_vec(1 , 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(2 , 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(3 , 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(4 , 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(5 , 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(6 , 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(7 , 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(8 , 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(9 , 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(10, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(11, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(12, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(13, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(14, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(15, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(16, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(17, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(18, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(19, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(20, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(21, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(22, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(23, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(24, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(25, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(26, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(27, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(28, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(29, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(30, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(31, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(32, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(33, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(34, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(35, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(36, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(37, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(38, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(39, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(40, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(41, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(42, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(43, 1  )/  -1.5075567228888181e-01 /
    data eigen_vec(44, 1  )/  -1.5075567228888181e-01 /

    ! ----------
    ! begin code
    ! ----------

    ! initalise amps
    do j = 1, ngraphs
        amp(j) = 0.d0
    end do

    ! external particles
    call ixxxxx(p1, fmass(3 ), nhel(1),  1, w1)
    call oxxxxx(p2, fmass(3 ), nhel(2), -1, w2)
    call oxxxxx(p3, fmass(12), nhel(3),  1, w3)
    call ixxxxx(p4, fmass(12), nhel(4), -1, w4)
    call ixxxxx(p5, fmass(1 ), nhel(5), -1, w5)
    call oxxxxx(p6, fmass(5 ), nhel(6),  1, w6)
    call oxxxxx(p7, fmass(2 ), nhel(7),  1, w7)
    call ixxxxx(p8, fmass(6 ), nhel(8), -1, w8)

    ! currents
    call jioxxx(w5, w7, gwf, wmass,wwidth, w10)
    call jioxxx(w8, w6, gwf, wmass, wwidth, w11)
    call jioxxx(w1, w2, gg, zero, zero, w28)
    call fvoxxx(w3, w10, gwf, fmass(11), fwidth(11), w29)
    call fvixxx(w4, w11, gwf, fmass(11), fwidth(11), w30)


    if (include_background == 1) then
        call jioxxx(w4 , w3 , gg, zero, zero, w9)
        call jioxxx(w5 , w7 , gwf,wmass,wwidth,w10 )
        call fvixxx(w1 , w10, gwf,fmass(4  ),fwidth(4  ),w12 )
        call fvoxxx(w2 , w11, gwf,fmass(4  ),fwidth(4  ),w13 )
        call fvoxxx(w2 , w9 , gg,fmass(3  ),fwidth(3  ),w14 )
        call jioxxx(w1 , w14, gau,amass,awidth,w15 )
        call jioxxx(w1 , w14, gzu,zmass,zwidth,w16 )
        call fvoxxx(w6 , w10, gwf,fmass(6  ),fwidth(6  ),w17 )
        call fvixxx(w8 , w10, gwf,fmass(5  ),fwidth(5  ),w18 )
        call fvixxx(w5 , w15, gal,fmass(1  ),fwidth(1  ),w19 )
        call fvixxx(w5 , w16, gzl,fmass(1  ),fwidth(1  ),w20 )
        call fvixxx(w5 , w11, gwf,fmass(2  ),fwidth(2  ),w21 )
        call fvixxx(w1 , w9 , gg,fmass(3  ),fwidth(3  ),w22 )
        call fvixxx(w22, w10, gwf,fmass(4  ),fwidth(4  ),w23 )
        call jioxxx(w22, w2 , gau,amass,awidth,w24 )
        call jioxxx(w22, w2 , gzu,zmass,zwidth,w25 )
        call fvixxx(w5 , w24, gal,fmass(1  ),fwidth(1  ),w26 )
        call fvixxx(w5 , w25, gzl,fmass(1  ),fwidth(1  ),w27 )
        call fvixxx(w4 , w28, gg,fmass(12 ),fwidth(12 ),w31 )
        call jioxxx(w31, w3 , gad,amass,awidth,w32 )
        call jioxxx(w31, w3 , gzd,zmass,zwidth,w33 )
        call hioxxx(w31, w3 , gchf(1,12 ),hmass,hwidth,w34 )
        call fvixxx(w8 , w33, gzn,fmass(6  ),fwidth(6  ),w35 )
        call fsixxx(w8 , w34, gchf(1,6  ),fmass(6  ),fwidth(6  ),w36 )
        call fvoxxx(w6 , w32, gal,fmass(5  ),fwidth(5  ),w37 )
        call fvoxxx(w6 , w33, gzl,fmass(5  ),fwidth(5  ),w38 )
        call fsoxxx(w6 , w34, gchf(1,5  ),fmass(5  ),fwidth(5  ),w39 )
        call fvixxx(w5 , w32, gal,fmass(1  ),fwidth(1  ),w40 )
        call jioxxx(w40, w7 , gwf,wmass,wwidth,w41 )
        call fvixxx(w5 , w33, gzl,fmass(1  ),fwidth(1  ),w42 )
        call jioxxx(w42, w7 , gwf,wmass,wwidth,w43 )
        call fvoxxx(w7 , w33, gzn,fmass(2  ),fwidth(2  ),w44 )
        call fvoxxx(w3 , w28, gg,fmass(12 ),fwidth(12 ),w45 )
        call fvoxxx(w45, w10, gwf,fmass(11 ),fwidth(11 ),w46 )
        call jioxxx(w4 , w45, gad,amass,awidth,w47 )
        call jioxxx(w4 , w45, gzd,zmass,zwidth,w48 )
        call hioxxx(w4 , w45, gchf(1,12 ),hmass,hwidth,w49 )
        call fvixxx(w8 , w48, gzn,fmass(6  ),fwidth(6  ),w50 )
        call fsixxx(w8 , w49, gchf(1,6  ),fmass(6  ),fwidth(6  ),w51 )
        call fvoxxx(w6 , w47, gal,fmass(5  ),fwidth(5  ),w52 )
        call fvoxxx(w6 , w48, gzl,fmass(5  ),fwidth(5  ),w53 )
        call fsoxxx(w6 , w49, gchf(1,5  ),fmass(5  ),fwidth(5  ),w54 )
        call fvixxx(w5 , w47, gal,fmass(1  ),fwidth(1  ),w55 )
        call jioxxx(w55, w7 , gwf,wmass,wwidth,w56 )
        call fvixxx(w5 , w48, gzl,fmass(1  ),fwidth(1  ),w57 )
        call jioxxx(w57, w7 , gwf,wmass,wwidth,w58 )
        call fvoxxx(w7 , w48, gzn,fmass(2  ),fwidth(2  ),w59 )
    end if

    ! amplitudes
    if (include_signal == 1) then
        call iovxxx(w30, w29, w28, gg, amp(20))
    end if

    if (include_background == 1) then
        call iovxxx(w12, w13, w9 , gg, amp(1))
        call vvvxxx(w11, w10, w15, gwwa, amp(2))
        call vvvxxx(w11, w10, w16, gwwz, amp(3))
        call iovxxx(w8 , w17, w16, gzn, amp(4))
        call iovxxx(w18, w6 , w15, gal, amp(5))
        call iovxxx(w18, w6 , w16, gzl, amp(6))
        call iovxxx(w19, w7 , w11, gwf, amp(7))
        call iovxxx(w20, w7 , w11, gwf, amp(8))
        call iovxxx(w21, w7 , w16, gzn, amp(9))
        call iovxxx(w12, w14, w11, gwf, amp(10))
        call iovxxx(w23, w2 , w11, gwf, amp(11))
        call vvvxxx(w11, w10, w24, gwwa, amp(12))
        call vvvxxx(w11, w10, w25, gwwz, amp(13))
        call iovxxx(w8 , w17, w25, gzn, amp(14))
        call iovxxx(w18, w6 , w24, gal, amp(15))
        call iovxxx(w18, w6 , w25, gzl, amp(16))
        call iovxxx(w26, w7 , w11, gwf, amp(17))
        call iovxxx(w27, w7 , w11, gwf, amp(18))
        call iovxxx(w21, w7 , w25, gzn, amp(19))
        call iovxxx(w30, w29, w28, gg, amp(20))
        call vvvxxx(w11, w10, w32, gwwa, amp(21))
        call vvvxxx(w11, w10, w33, gwwz, amp(22))
        call vvsxxx(w11, w10, w34, gwwh, amp(23))
        call iovxxx(w35, w6 , w10, gwf, amp(24))
        call iovxxx(w36, w6 , w10, gwf, amp(25))
        call iovxxx(w8 , w37, w10, gwf, amp(26))
        call iovxxx(w8 , w38, w10, gwf, amp(27))
        call iovxxx(w8 , w39, w10, gwf, amp(28))
        call iovxxx(w8 , w6 , w41, gwf, amp(29))
        call iovxxx(w8 , w6 , w43, gwf, amp(30))
        call iovxxx(w5 , w44, w11, gwf, amp(31))
        call iovxxx(w31, w29, w11, gwf, amp(32))
        call iovxxx(w4 , w46, w11, gwf, amp(33))
        call vvvxxx(w11, w10, w47, gwwa, amp(34))
        call vvvxxx(w11, w10, w48, gwwz, amp(35))
        call vvsxxx(w11, w10, w49, gwwh, amp(36))
        call iovxxx(w50, w6 , w10, gwf, amp(37))
        call iovxxx(w51, w6 , w10, gwf, amp(38))
        call iovxxx(w8 , w52, w10, gwf, amp(39))
        call iovxxx(w8 , w53, w10, gwf, amp(40))
        call iovxxx(w8 , w54, w10, gwf, amp(41))
        call iovxxx(w8 , w6 , w56, gwf, amp(42))
        call iovxxx(w8 , w6 , w58, gwf, amp(43))
        call iovxxx(w5 , w59, w11, gwf, amp(44))
    end if

    qq_bbemuvevm = 0.d0
    do i = 1, neigen
        ztemp = (0.d0,0.d0)
        do j = 1, ngraphs
            ztemp = ztemp + eigen_vec(j,i)*amp(j)
        enddo
        qq_bbemuvevm = qq_bbemuvevm + ztemp*eigen_val(i)*conjg(ztemp)
    enddo
    ! call gaugecheck(amp, ztemp, eigen_vec, eigen_val, ngraphs, neigen)
end function qq_bbemuvevm
